#!/bin/bash -u

source $(dirname ${BASH_SOURCE[0]})/import_all.sh;

async_wait_functions \
    "getent hosts 1.localhost.mene.ro"\
    "getent hosts 2.localhost.mene.ro"\
    "getent hosts 3.localhost.mene.ro"\
    "getent hosts 4.localhost.mene.ro"\
    "getent hosts 5.localhost.mene.ro"\
    "getent hosts 6.localhost.mene.ro"\
    "getent hosts 7.localhost.mene.ro"\
    "getent hosts 8.localhost.mene.ro"\
    "getent hosts 9.localhost.mene.ro"\
    "getent hosts 10.localhost.mene.ro"\
    "getent hosts 11.localhost.mene.ro"\
    "getent hosts 12.localhost.mene.ro"\
    "getent hosts 13.localhost.mene.ro"\
    "getent hosts 14.localhost.mene.ro"\
    "getent hosts 15.localhost.mene.ro"\
    "getent hosts 16.localhost.mene.ro"\
    "getent hosts 17.localhost.mene.ro"\
    "getent hosts 18.localhost.mene.ro"\
    "getent hosts 19.localhost.mene.ro"\
    "getent hosts 20.localhost.mene.ro"\
    "getent hosts 21.localhost.mene.ro"\
    "getent hosts 22.localhost.mene.ro"\
    "getent hosts 23.localhost.mene.ro"\
    "getent hosts 24.localhost.mene.ro"\
    "getent hosts 25.localhost.mene.ro"\
    "getent hosts 26.localhost.mene.ro"\
    "getent hosts 27.localhost.mene.ro"\
    "getent hosts 28.localhost.mene.ro"\
    "getent hosts 29.localhost.mene.ro"\
    "getent hosts 30.localhost.mene.ro"\
    "getent hosts 31.localhost.mene.ro"\
    "getent hosts 32.localhost.mene.ro"\
    "getent hosts 33.localhost.mene.ro"\
    "getent hosts 34.localhost.mene.ro"\
    "getent hosts 35.localhost.mene.ro"\
    "getent hosts 36.localhost.mene.ro"\
    "getent hosts 37.localhost.mene.ro"\
    "getent hosts 38.localhost.mene.ro"\
    "getent hosts 39.localhost.mene.ro"\
    "getent hosts 40.localhost.mene.ro"\
    "getent hosts 41.localhost.mene.ro"\
    "getent hosts 42.localhost.mene.ro"\
    "getent hosts 43.localhost.mene.ro"\
    "getent hosts 44.localhost.mene.ro"\
    "getent hosts 45.localhost.mene.ro"\
    "getent hosts 46.localhost.mene.ro"\
    "getent hosts 47.localhost.mene.ro"\
    "getent hosts 48.localhost.mene.ro"\
    "getent hosts 49.localhost.mene.ro"\
    "getent hosts 50.localhost.mene.ro"\
    "getent hosts 51.localhost.mene.ro"\
    "getent hosts 52.localhost.mene.ro"\
    "getent hosts 53.localhost.mene.ro"\
    "getent hosts 54.localhost.mene.ro"\
    "getent hosts 55.localhost.mene.ro"\
    "getent hosts 56.localhost.mene.ro"\
    "getent hosts 57.localhost.mene.ro"\
    "getent hosts 58.localhost.mene.ro"\
    "getent hosts 59.localhost.mene.ro"\
    "getent hosts 60.localhost.mene.ro"\
    "getent hosts 61.localhost.mene.ro"\
    "getent hosts 62.localhost.mene.ro"\
    "getent hosts 63.localhost.mene.ro"\
    "getent hosts 64.localhost.mene.ro"\
    "getent hosts 65.localhost.mene.ro"\
    "getent hosts 66.localhost.mene.ro"\
    "getent hosts 67.localhost.mene.ro"\
    "getent hosts 68.localhost.mene.ro"\
    "getent hosts 69.localhost.mene.ro"\
    "getent hosts 70.localhost.mene.ro"\
    "getent hosts 71.localhost.mene.ro"\
    "getent hosts 72.localhost.mene.ro"\
    "getent hosts 73.localhost.mene.ro"\
    "getent hosts 74.localhost.mene.ro"\
    "getent hosts 75.localhost.mene.ro"\
    "getent hosts 76.localhost.mene.ro"\
    "getent hosts 77.localhost.mene.ro"\
    "getent hosts 78.localhost.mene.ro"\
    "getent hosts 79.localhost.mene.ro"\
    "getent hosts 80.localhost.mene.ro"\
    "getent hosts 81.localhost.mene.ro"\
    "getent hosts 82.localhost.mene.ro"\
    "getent hosts 83.localhost.mene.ro"\
    "getent hosts 84.localhost.mene.ro"\
    "getent hosts 85.localhost.mene.ro"\
    "getent hosts 86.localhost.mene.ro"\
    "getent hosts 87.localhost.mene.ro"\
    "getent hosts 88.localhost.mene.ro"\
    "getent hosts 89.localhost.mene.ro"\
    "getent hosts 90.localhost.mene.ro"\
    "getent hosts 91.localhost.mene.ro"\
    "getent hosts 92.localhost.mene.ro"\
    "getent hosts 93.localhost.mene.ro"\
    "getent hosts 94.localhost.mene.ro"\
    "getent hosts 95.localhost.mene.ro"\
    "getent hosts 96.localhost.mene.ro"\
    "getent hosts 97.localhost.mene.ro"\
    "getent hosts 98.localhost.mene.ro"\
    "getent hosts 99.localhost.mene.ro"\
    "getent hosts 100.localhost.mene.ro"\
    "getent hosts 101.localhost.mene.ro"\
    "getent hosts 102.localhost.mene.ro"\
    "getent hosts 103.localhost.mene.ro"\
    "getent hosts 104.localhost.mene.ro"\
    "getent hosts 105.localhost.mene.ro"\
    "getent hosts 106.localhost.mene.ro"\
    "getent hosts 107.localhost.mene.ro"\
    "getent hosts 108.localhost.mene.ro"\
    "getent hosts 109.localhost.mene.ro"\
    "getent hosts 110.localhost.mene.ro"\
    "getent hosts 111.localhost.mene.ro"\
    "getent hosts 112.localhost.mene.ro"\
    "getent hosts 113.localhost.mene.ro"\
    "getent hosts 114.localhost.mene.ro"\
    "getent hosts 115.localhost.mene.ro"\
    "getent hosts 116.localhost.mene.ro"\
    "getent hosts 117.localhost.mene.ro"\
    "getent hosts 118.localhost.mene.ro"\
    "getent hosts 119.localhost.mene.ro"\
    "getent hosts 120.localhost.mene.ro"\
    "getent hosts 121.localhost.mene.ro"\
    "getent hosts 122.localhost.mene.ro"\
    "getent hosts 123.localhost.mene.ro"\
    "getent hosts 124.localhost.mene.ro"\
    "getent hosts 125.localhost.mene.ro"\
    "getent hosts 126.localhost.mene.ro"\
    "getent hosts 127.localhost.mene.ro"\
    "getent hosts 128.localhost.mene.ro"\
    "getent hosts 129.localhost.mene.ro"\
    "getent hosts 130.localhost.mene.ro"\
    "getent hosts 131.localhost.mene.ro"\
    "getent hosts 132.localhost.mene.ro"\
    "getent hosts 133.localhost.mene.ro"\
    "getent hosts 134.localhost.mene.ro"\
    "getent hosts 135.localhost.mene.ro"\
    "getent hosts 136.localhost.mene.ro"\
    "getent hosts 137.localhost.mene.ro"\
    "getent hosts 138.localhost.mene.ro"\
    "getent hosts 139.localhost.mene.ro"\
    "getent hosts 140.localhost.mene.ro"\
    "getent hosts 141.localhost.mene.ro"\
    "getent hosts 142.localhost.mene.ro"\
    "getent hosts 143.localhost.mene.ro"\
    "getent hosts 144.localhost.mene.ro"\
    "getent hosts 145.localhost.mene.ro"\
    "getent hosts 146.localhost.mene.ro"\
    "getent hosts 147.localhost.mene.ro"\
    "getent hosts 148.localhost.mene.ro"\
    "getent hosts 149.localhost.mene.ro"\
    "getent hosts 150.localhost.mene.ro"\
    "getent hosts 151.localhost.mene.ro"\
    "getent hosts 152.localhost.mene.ro"\
    "getent hosts 153.localhost.mene.ro"\
    "getent hosts 154.localhost.mene.ro"\
    "getent hosts 155.localhost.mene.ro"\
    "getent hosts 156.localhost.mene.ro"\
    "getent hosts 157.localhost.mene.ro"\
    "getent hosts 158.localhost.mene.ro"\
    "getent hosts 159.localhost.mene.ro"\
    "getent hosts 160.localhost.mene.ro"\
    "getent hosts 161.localhost.mene.ro"\
    "getent hosts 162.localhost.mene.ro"\
    "getent hosts 163.localhost.mene.ro"\
    "getent hosts 164.localhost.mene.ro"\
    "getent hosts 165.localhost.mene.ro"\
    "getent hosts 166.localhost.mene.ro"\
    "getent hosts 167.localhost.mene.ro"\
    "getent hosts 168.localhost.mene.ro"\
    "getent hosts 169.localhost.mene.ro"\
    "getent hosts 170.localhost.mene.ro"\
    "getent hosts 171.localhost.mene.ro"\
    "getent hosts 172.localhost.mene.ro"\
    "getent hosts 173.localhost.mene.ro"\
    "getent hosts 174.localhost.mene.ro"\
    "getent hosts 175.localhost.mene.ro"\
    "getent hosts 176.localhost.mene.ro"\
    "getent hosts 177.localhost.mene.ro"\
    "getent hosts 178.localhost.mene.ro"\
    "getent hosts 179.localhost.mene.ro"\
    "getent hosts 180.localhost.mene.ro"\
    "getent hosts 181.localhost.mene.ro"\
    "getent hosts 182.localhost.mene.ro"\
    "getent hosts 183.localhost.mene.ro"\
    "getent hosts 184.localhost.mene.ro"\
    "getent hosts 185.localhost.mene.ro"\
    "getent hosts 186.localhost.mene.ro"\
    "getent hosts 187.localhost.mene.ro"\
    "getent hosts 188.localhost.mene.ro"\
    "getent hosts 189.localhost.mene.ro"\
    "getent hosts 190.localhost.mene.ro"\
    "getent hosts 191.localhost.mene.ro"\
    "getent hosts 192.localhost.mene.ro"\
    "getent hosts 193.localhost.mene.ro"\
    "getent hosts 194.localhost.mene.ro"\
    "getent hosts 195.localhost.mene.ro"\
    "getent hosts 196.localhost.mene.ro"\
    "getent hosts 197.localhost.mene.ro"\
    "getent hosts 198.localhost.mene.ro"\
    "getent hosts 199.localhost.mene.ro"\
    "getent hosts 200.localhost.mene.ro"\
    "getent hosts 201.localhost.mene.ro"\
    "getent hosts 202.localhost.mene.ro"\
    "getent hosts 203.localhost.mene.ro"\
    "getent hosts 204.localhost.mene.ro"\
    "getent hosts 205.localhost.mene.ro"\
    "getent hosts 206.localhost.mene.ro"\
    "getent hosts 207.localhost.mene.ro"\
    "getent hosts 208.localhost.mene.ro"\
    "getent hosts 209.localhost.mene.ro"\
    "getent hosts 210.localhost.mene.ro"\
    "getent hosts 211.localhost.mene.ro"\
    "getent hosts 212.localhost.mene.ro"\
    "getent hosts 213.localhost.mene.ro"\
    "getent hosts 214.localhost.mene.ro"\
    "getent hosts 215.localhost.mene.ro"\
    "getent hosts 216.localhost.mene.ro"\
    "getent hosts 217.localhost.mene.ro"\
    "getent hosts 218.localhost.mene.ro"\
    "getent hosts 219.localhost.mene.ro"\
    "getent hosts 220.localhost.mene.ro"\
    "getent hosts 221.localhost.mene.ro"\
    "getent hosts 222.localhost.mene.ro"\
    "getent hosts 223.localhost.mene.ro"\
    "getent hosts 224.localhost.mene.ro"\
    "getent hosts 225.localhost.mene.ro"\
    "getent hosts 226.localhost.mene.ro"\
    "getent hosts 227.localhost.mene.ro"\
    "getent hosts 228.localhost.mene.ro"\
    "getent hosts 229.localhost.mene.ro"\
    "getent hosts 230.localhost.mene.ro"\
    "getent hosts 231.localhost.mene.ro"\
    "getent hosts 232.localhost.mene.ro"\
    "getent hosts 233.localhost.mene.ro"\
    "getent hosts 234.localhost.mene.ro"\
    "getent hosts 235.localhost.mene.ro"\
    "getent hosts 236.localhost.mene.ro"\
    "getent hosts 237.localhost.mene.ro"\
    "getent hosts 238.localhost.mene.ro"\
    "getent hosts 239.localhost.mene.ro"\
    "getent hosts 240.localhost.mene.ro"\
    "getent hosts 241.localhost.mene.ro"\
    "getent hosts 242.localhost.mene.ro"\
    "getent hosts 243.localhost.mene.ro"\
    "getent hosts 244.localhost.mene.ro"\
    "getent hosts 245.localhost.mene.ro"\
    "getent hosts 246.localhost.mene.ro"\
    "getent hosts 247.localhost.mene.ro"\
    "getent hosts 248.localhost.mene.ro"\
    "getent hosts 249.localhost.mene.ro"\
    "getent hosts 250.localhost.mene.ro"\
    "getent hosts 251.localhost.mene.ro"\
    "getent hosts 252.localhost.mene.ro"\
    "getent hosts 253.localhost.mene.ro"\
    "getent hosts 254.localhost.mene.ro"\
    "getent hosts 255.localhost.mene.ro"\
    "getent hosts 256.localhost.mene.ro"\
    "getent hosts 257.localhost.mene.ro"\
    "getent hosts 258.localhost.mene.ro"\
    "getent hosts 259.localhost.mene.ro"\
    "getent hosts 260.localhost.mene.ro"\
    "getent hosts 261.localhost.mene.ro"\
    "getent hosts 262.localhost.mene.ro"\
    "getent hosts 263.localhost.mene.ro"\
    "getent hosts 264.localhost.mene.ro"\
    "getent hosts 265.localhost.mene.ro"\
    "getent hosts 266.localhost.mene.ro"\
    "getent hosts 267.localhost.mene.ro"\
    "getent hosts 268.localhost.mene.ro"\
    "getent hosts 269.localhost.mene.ro"\
    "getent hosts 270.localhost.mene.ro"\
    "getent hosts 271.localhost.mene.ro"\
    "getent hosts 272.localhost.mene.ro"\
    "getent hosts 273.localhost.mene.ro"\
    "getent hosts 274.localhost.mene.ro"\
    "getent hosts 275.localhost.mene.ro"\
    "getent hosts 276.localhost.mene.ro"\
    "getent hosts 277.localhost.mene.ro"\
    "getent hosts 278.localhost.mene.ro"\
    "getent hosts 279.localhost.mene.ro"\
    "getent hosts 280.localhost.mene.ro"\
    "getent hosts 281.localhost.mene.ro"\
    "getent hosts 282.localhost.mene.ro"\
    "getent hosts 283.localhost.mene.ro"\
    "getent hosts 284.localhost.mene.ro"\
    "getent hosts 285.localhost.mene.ro"\
    "getent hosts 286.localhost.mene.ro"\
    "getent hosts 287.localhost.mene.ro"\
    "getent hosts 288.localhost.mene.ro"\
    "getent hosts 289.localhost.mene.ro"\
    "getent hosts 290.localhost.mene.ro"\
    "getent hosts 291.localhost.mene.ro"\
    "getent hosts 292.localhost.mene.ro"\
    "getent hosts 293.localhost.mene.ro"\
    "getent hosts 294.localhost.mene.ro"\
    "getent hosts 295.localhost.mene.ro"\
    "getent hosts 296.localhost.mene.ro"\
    "getent hosts 297.localhost.mene.ro"\
    "getent hosts 298.localhost.mene.ro"\
    "getent hosts 299.localhost.mene.ro"\
    "getent hosts 300.localhost.mene.ro"\
    "getent hosts 301.localhost.mene.ro"\
    "getent hosts 302.localhost.mene.ro"\
    "getent hosts 303.localhost.mene.ro"\
    "getent hosts 304.localhost.mene.ro"\
    "getent hosts 305.localhost.mene.ro"\
    "getent hosts 306.localhost.mene.ro"\
    "getent hosts 307.localhost.mene.ro"\
    "getent hosts 308.localhost.mene.ro"\
    "getent hosts 309.localhost.mene.ro"\
    "getent hosts 310.localhost.mene.ro"\
    "getent hosts 311.localhost.mene.ro"\
    "getent hosts 312.localhost.mene.ro"\
    "getent hosts 313.localhost.mene.ro"\
    "getent hosts 314.localhost.mene.ro"\
    "getent hosts 315.localhost.mene.ro"\
    "getent hosts 316.localhost.mene.ro"\
    "getent hosts 317.localhost.mene.ro"\
    "getent hosts 318.localhost.mene.ro"\
    "getent hosts 319.localhost.mene.ro"\
    "getent hosts 320.localhost.mene.ro"\
    "getent hosts 321.localhost.mene.ro"\
    "getent hosts 322.localhost.mene.ro"\
    "getent hosts 323.localhost.mene.ro"\
    "getent hosts 324.localhost.mene.ro"\
    "getent hosts 325.localhost.mene.ro"\
    "getent hosts 326.localhost.mene.ro"\
    "getent hosts 327.localhost.mene.ro"\
    "getent hosts 328.localhost.mene.ro"\
    "getent hosts 329.localhost.mene.ro"\
    "getent hosts 330.localhost.mene.ro"\
    "getent hosts 331.localhost.mene.ro"\
    "getent hosts 332.localhost.mene.ro"\
    "getent hosts 333.localhost.mene.ro"\
    "getent hosts 334.localhost.mene.ro"\
    "getent hosts 335.localhost.mene.ro"\
    "getent hosts 336.localhost.mene.ro"\
    "getent hosts 337.localhost.mene.ro"\
    "getent hosts 338.localhost.mene.ro"\
    "getent hosts 339.localhost.mene.ro"\
    "getent hosts 340.localhost.mene.ro"\
    "getent hosts 341.localhost.mene.ro"\
    "getent hosts 342.localhost.mene.ro"\
    "getent hosts 343.localhost.mene.ro"\
    "getent hosts 344.localhost.mene.ro"\
    "getent hosts 345.localhost.mene.ro"\
    "getent hosts 346.localhost.mene.ro"\
    "getent hosts 347.localhost.mene.ro"\
    "getent hosts 348.localhost.mene.ro"\
    "getent hosts 349.localhost.mene.ro"\
    "getent hosts 350.localhost.mene.ro"\
    "getent hosts 351.localhost.mene.ro"\
    "getent hosts 352.localhost.mene.ro"\
    "getent hosts 353.localhost.mene.ro"\
    "getent hosts 354.localhost.mene.ro"\
    "getent hosts 355.localhost.mene.ro"\
    "getent hosts 356.localhost.mene.ro"\
    "getent hosts 357.localhost.mene.ro"\
    "getent hosts 358.localhost.mene.ro"\
    "getent hosts 359.localhost.mene.ro"\
    "getent hosts 360.localhost.mene.ro"\
    "getent hosts 361.localhost.mene.ro"\
    "getent hosts 362.localhost.mene.ro"\
    "getent hosts 363.localhost.mene.ro"\
    "getent hosts 364.localhost.mene.ro"\
    "getent hosts 365.localhost.mene.ro"\
    "getent hosts 366.localhost.mene.ro"\
    "getent hosts 367.localhost.mene.ro"\
    "getent hosts 368.localhost.mene.ro"\
    "getent hosts 369.localhost.mene.ro"\
    "getent hosts 370.localhost.mene.ro"\
    "getent hosts 371.localhost.mene.ro"\
    "getent hosts 372.localhost.mene.ro"\
    "getent hosts 373.localhost.mene.ro"\
    "getent hosts 374.localhost.mene.ro"\
    "getent hosts 375.localhost.mene.ro"\
    "getent hosts 376.localhost.mene.ro"\
    "getent hosts 377.localhost.mene.ro"\
    "getent hosts 378.localhost.mene.ro"\
    "getent hosts 379.localhost.mene.ro"\
    "getent hosts 380.localhost.mene.ro"\
    "getent hosts 381.localhost.mene.ro"\
    "getent hosts 382.localhost.mene.ro"\
    "getent hosts 383.localhost.mene.ro"\
    "getent hosts 384.localhost.mene.ro"\
    "getent hosts 385.localhost.mene.ro"\
    "getent hosts 386.localhost.mene.ro"\
    "getent hosts 387.localhost.mene.ro"\
    "getent hosts 388.localhost.mene.ro"\
    "getent hosts 389.localhost.mene.ro"\
    "getent hosts 390.localhost.mene.ro"\
    "getent hosts 391.localhost.mene.ro"\
    "getent hosts 392.localhost.mene.ro"\
    "getent hosts 393.localhost.mene.ro"\
    "getent hosts 394.localhost.mene.ro"\
    "getent hosts 395.localhost.mene.ro"\
    "getent hosts 396.localhost.mene.ro"\
    "getent hosts 397.localhost.mene.ro"\
    "getent hosts 398.localhost.mene.ro"\
    "getent hosts 399.localhost.mene.ro"\
    "getent hosts 400.localhost.mene.ro"\
    "getent hosts 401.localhost.mene.ro"\
    "getent hosts 402.localhost.mene.ro"\
    "getent hosts 403.localhost.mene.ro"\
    "getent hosts 404.localhost.mene.ro"\
    "getent hosts 405.localhost.mene.ro"\
    "getent hosts 406.localhost.mene.ro"\
    "getent hosts 407.localhost.mene.ro"\
    "getent hosts 408.localhost.mene.ro"\
    "getent hosts 409.localhost.mene.ro"\
    "getent hosts 410.localhost.mene.ro"\
    "getent hosts 411.localhost.mene.ro"\
    "getent hosts 412.localhost.mene.ro"\
    "getent hosts 413.localhost.mene.ro"\
    "getent hosts 414.localhost.mene.ro"\
    "getent hosts 415.localhost.mene.ro"\
    "getent hosts 416.localhost.mene.ro"\
    "getent hosts 417.localhost.mene.ro"\
    "getent hosts 418.localhost.mene.ro"\
    "getent hosts 419.localhost.mene.ro"\
    "getent hosts 420.localhost.mene.ro"\
    "getent hosts 421.localhost.mene.ro"\
    "getent hosts 422.localhost.mene.ro"\
    "getent hosts 423.localhost.mene.ro"\
    "getent hosts 424.localhost.mene.ro"\
    "getent hosts 425.localhost.mene.ro"\
    "getent hosts 426.localhost.mene.ro"\
    "getent hosts 427.localhost.mene.ro"\
    "getent hosts 428.localhost.mene.ro"\
    "getent hosts 429.localhost.mene.ro"\
    "getent hosts 430.localhost.mene.ro"\
    "getent hosts 431.localhost.mene.ro"\
    "getent hosts 432.localhost.mene.ro"\
    "getent hosts 433.localhost.mene.ro"\
    "getent hosts 434.localhost.mene.ro"\
    "getent hosts 435.localhost.mene.ro"\
    "getent hosts 436.localhost.mene.ro"\
    "getent hosts 437.localhost.mene.ro"\
    "getent hosts 438.localhost.mene.ro"\
    "getent hosts 439.localhost.mene.ro"\
    "getent hosts 440.localhost.mene.ro"\
    "getent hosts 441.localhost.mene.ro"\
    "getent hosts 442.localhost.mene.ro"\
    "getent hosts 443.localhost.mene.ro"\
    "getent hosts 444.localhost.mene.ro"\
    "getent hosts 445.localhost.mene.ro"\
    "getent hosts 446.localhost.mene.ro"\
    "getent hosts 447.localhost.mene.ro"\
    "getent hosts 448.localhost.mene.ro"\
    "getent hosts 449.localhost.mene.ro"\
    "getent hosts 450.localhost.mene.ro"\
    "getent hosts 451.localhost.mene.ro"\
    "getent hosts 452.localhost.mene.ro"\
    "getent hosts 453.localhost.mene.ro"\
    "getent hosts 454.localhost.mene.ro"\
    "getent hosts 455.localhost.mene.ro"\
    "getent hosts 456.localhost.mene.ro"\
    "getent hosts 457.localhost.mene.ro"\
    "getent hosts 458.localhost.mene.ro"\
    "getent hosts 459.localhost.mene.ro"\
    "getent hosts 460.localhost.mene.ro"\
    "getent hosts 461.localhost.mene.ro"\
    "getent hosts 462.localhost.mene.ro"\
    "getent hosts 463.localhost.mene.ro"\
    "getent hosts 464.localhost.mene.ro"\
    "getent hosts 465.localhost.mene.ro"\
    "getent hosts 466.localhost.mene.ro"\
    "getent hosts 467.localhost.mene.ro"\
    "getent hosts 468.localhost.mene.ro"\
    "getent hosts 469.localhost.mene.ro"\
    "getent hosts 470.localhost.mene.ro"\
    "getent hosts 471.localhost.mene.ro"\
    "getent hosts 472.localhost.mene.ro"\
    "getent hosts 473.localhost.mene.ro"\
    "getent hosts 474.localhost.mene.ro"\
    "getent hosts 475.localhost.mene.ro"\
    "getent hosts 476.localhost.mene.ro"\
    "getent hosts 477.localhost.mene.ro"\
    "getent hosts 478.localhost.mene.ro"\
    "getent hosts 479.localhost.mene.ro"\
    "getent hosts 480.localhost.mene.ro"\
    "getent hosts 481.localhost.mene.ro"\
    "getent hosts 482.localhost.mene.ro"\
    "getent hosts 483.localhost.mene.ro"\
    "getent hosts 484.localhost.mene.ro"\
    "getent hosts 485.localhost.mene.ro"\
    "getent hosts 486.localhost.mene.ro"\
    "getent hosts 487.localhost.mene.ro"\
    "getent hosts 488.localhost.mene.ro"\
    "getent hosts 489.localhost.mene.ro"\
    "getent hosts 490.localhost.mene.ro"\
    "getent hosts 491.localhost.mene.ro"\
    "getent hosts 492.localhost.mene.ro"\
    "getent hosts 493.localhost.mene.ro"\
    "getent hosts 494.localhost.mene.ro"\
    "getent hosts 495.localhost.mene.ro"\
    "getent hosts 496.localhost.mene.ro"\
    "getent hosts 497.localhost.mene.ro"\
    "getent hosts 498.localhost.mene.ro"\
    "getent hosts 499.localhost.mene.ro"\
    "getent hosts 500.localhost.mene.ro"\
    "getent hosts 501.localhost.mene.ro"\
    "getent hosts 502.localhost.mene.ro"\
    "getent hosts 503.localhost.mene.ro"\
    "getent hosts 504.localhost.mene.ro"\
    "getent hosts 505.localhost.mene.ro"\
    "getent hosts 506.localhost.mene.ro"\
    "getent hosts 507.localhost.mene.ro"\
    "getent hosts 508.localhost.mene.ro"\
    "getent hosts 509.localhost.mene.ro"\
    "getent hosts 510.localhost.mene.ro"\
    "getent hosts 511.localhost.mene.ro"\
    "getent hosts 512.localhost.mene.ro"\
    "getent hosts 513.localhost.mene.ro"\
    "getent hosts 514.localhost.mene.ro"\
    "getent hosts 515.localhost.mene.ro"\
    "getent hosts 516.localhost.mene.ro"\
    "getent hosts 517.localhost.mene.ro"\
    "getent hosts 518.localhost.mene.ro"\
    "getent hosts 519.localhost.mene.ro"\
    "getent hosts 520.localhost.mene.ro"\
    "getent hosts 521.localhost.mene.ro"\
    "getent hosts 522.localhost.mene.ro"\
    "getent hosts 523.localhost.mene.ro"\
    "getent hosts 524.localhost.mene.ro"\
    "getent hosts 525.localhost.mene.ro"\
    "getent hosts 526.localhost.mene.ro"\
    "getent hosts 527.localhost.mene.ro"\
    "getent hosts 528.localhost.mene.ro"\
    "getent hosts 529.localhost.mene.ro"\
    "getent hosts 530.localhost.mene.ro"\
    "getent hosts 531.localhost.mene.ro"\
    "getent hosts 532.localhost.mene.ro"\
    "getent hosts 533.localhost.mene.ro"\
    "getent hosts 534.localhost.mene.ro"\
    "getent hosts 535.localhost.mene.ro"\
    "getent hosts 536.localhost.mene.ro"\
    "getent hosts 537.localhost.mene.ro"\
    "getent hosts 538.localhost.mene.ro"\
    "getent hosts 539.localhost.mene.ro"\
    "getent hosts 540.localhost.mene.ro"\
    "getent hosts 541.localhost.mene.ro"\
    "getent hosts 542.localhost.mene.ro"\
    "getent hosts 543.localhost.mene.ro"\
    "getent hosts 544.localhost.mene.ro"\
    "getent hosts 545.localhost.mene.ro"\
    "getent hosts 546.localhost.mene.ro"\
    "getent hosts 547.localhost.mene.ro"\
    "getent hosts 548.localhost.mene.ro"\
    "getent hosts 549.localhost.mene.ro"\
    "getent hosts 550.localhost.mene.ro"\
    "getent hosts 551.localhost.mene.ro"\
    "getent hosts 552.localhost.mene.ro"\
    "getent hosts 553.localhost.mene.ro"\
    "getent hosts 554.localhost.mene.ro"\
    "getent hosts 555.localhost.mene.ro"\
    "getent hosts 556.localhost.mene.ro"\
    "getent hosts 557.localhost.mene.ro"\
    "getent hosts 558.localhost.mene.ro"\
    "getent hosts 559.localhost.mene.ro"\
    "getent hosts 560.localhost.mene.ro"\
    "getent hosts 561.localhost.mene.ro"\
    "getent hosts 562.localhost.mene.ro"\
    "getent hosts 563.localhost.mene.ro"\
    "getent hosts 564.localhost.mene.ro"\
    "getent hosts 565.localhost.mene.ro"\
    "getent hosts 566.localhost.mene.ro"\
    "getent hosts 567.localhost.mene.ro"\
    "getent hosts 568.localhost.mene.ro"\
    "getent hosts 569.localhost.mene.ro"\
    "getent hosts 570.localhost.mene.ro"\
    "getent hosts 571.localhost.mene.ro"\
    "getent hosts 572.localhost.mene.ro"\
    "getent hosts 573.localhost.mene.ro"\
    "getent hosts 574.localhost.mene.ro"\
    "getent hosts 575.localhost.mene.ro"\
    "getent hosts 576.localhost.mene.ro"\
    "getent hosts 577.localhost.mene.ro"\
    "getent hosts 578.localhost.mene.ro"\
    "getent hosts 579.localhost.mene.ro"\
    "getent hosts 580.localhost.mene.ro"\
    "getent hosts 581.localhost.mene.ro"\
    "getent hosts 582.localhost.mene.ro"\
    "getent hosts 583.localhost.mene.ro"\
    "getent hosts 584.localhost.mene.ro"\
    "getent hosts 585.localhost.mene.ro"\
    "getent hosts 586.localhost.mene.ro"\
    "getent hosts 587.localhost.mene.ro"\
    "getent hosts 588.localhost.mene.ro"\
    "getent hosts 589.localhost.mene.ro"\
    "getent hosts 590.localhost.mene.ro"\
    "getent hosts 591.localhost.mene.ro"\
    "getent hosts 592.localhost.mene.ro"\
    "getent hosts 593.localhost.mene.ro"\
    "getent hosts 594.localhost.mene.ro"\
    "getent hosts 595.localhost.mene.ro"\
    "getent hosts 596.localhost.mene.ro"\
    "getent hosts 597.localhost.mene.ro"\
    "getent hosts 598.localhost.mene.ro"\
    "getent hosts 599.localhost.mene.ro"\
    "getent hosts 600.localhost.mene.ro"\
    "getent hosts 601.localhost.mene.ro"\
    "getent hosts 602.localhost.mene.ro"\
    "getent hosts 603.localhost.mene.ro"\
    "getent hosts 604.localhost.mene.ro"\
    "getent hosts 605.localhost.mene.ro"\
    "getent hosts 606.localhost.mene.ro"\
    "getent hosts 607.localhost.mene.ro"\
    "getent hosts 608.localhost.mene.ro"\
    "getent hosts 609.localhost.mene.ro"\
    "getent hosts 610.localhost.mene.ro"\
    "getent hosts 611.localhost.mene.ro"\
    "getent hosts 612.localhost.mene.ro"\
    "getent hosts 613.localhost.mene.ro"\
    "getent hosts 614.localhost.mene.ro"\
    "getent hosts 615.localhost.mene.ro"\
    "getent hosts 616.localhost.mene.ro"\
    "getent hosts 617.localhost.mene.ro"\
    "getent hosts 618.localhost.mene.ro"\
    "getent hosts 619.localhost.mene.ro"\
    "getent hosts 620.localhost.mene.ro"\
    "getent hosts 621.localhost.mene.ro"\
    "getent hosts 622.localhost.mene.ro"\
    "getent hosts 623.localhost.mene.ro"\
    "getent hosts 624.localhost.mene.ro"\
    "getent hosts 625.localhost.mene.ro"\
    "getent hosts 626.localhost.mene.ro"\
    "getent hosts 627.localhost.mene.ro"\
    "getent hosts 628.localhost.mene.ro"\
    "getent hosts 629.localhost.mene.ro"\
    "getent hosts 630.localhost.mene.ro"\
    "getent hosts 631.localhost.mene.ro"\
    "getent hosts 632.localhost.mene.ro"\
    "getent hosts 633.localhost.mene.ro"\
    "getent hosts 634.localhost.mene.ro"\
    "getent hosts 635.localhost.mene.ro"\
    "getent hosts 636.localhost.mene.ro"\
    "getent hosts 637.localhost.mene.ro"\
    "getent hosts 638.localhost.mene.ro"\
    "getent hosts 639.localhost.mene.ro"\
    "getent hosts 640.localhost.mene.ro"\
    "getent hosts 641.localhost.mene.ro"\
    "getent hosts 642.localhost.mene.ro"\
    "getent hosts 643.localhost.mene.ro"\
    "getent hosts 644.localhost.mene.ro"\
    "getent hosts 645.localhost.mene.ro"\
    "getent hosts 646.localhost.mene.ro"\
    "getent hosts 647.localhost.mene.ro"\
    "getent hosts 648.localhost.mene.ro"\
    "getent hosts 649.localhost.mene.ro"\
    "getent hosts 650.localhost.mene.ro"\
    "getent hosts 651.localhost.mene.ro"\
    "getent hosts 652.localhost.mene.ro"\
    "getent hosts 653.localhost.mene.ro"\
    "getent hosts 654.localhost.mene.ro"\
    "getent hosts 655.localhost.mene.ro"\
    "getent hosts 656.localhost.mene.ro"\
    "getent hosts 657.localhost.mene.ro"\
    "getent hosts 658.localhost.mene.ro"\
    "getent hosts 659.localhost.mene.ro"\
    "getent hosts 660.localhost.mene.ro"\
    "getent hosts 661.localhost.mene.ro"\
    "getent hosts 662.localhost.mene.ro"\
    "getent hosts 663.localhost.mene.ro"\
    "getent hosts 664.localhost.mene.ro"\
    "getent hosts 665.localhost.mene.ro"\
    "getent hosts 666.localhost.mene.ro"\
    "getent hosts 667.localhost.mene.ro"\
    "getent hosts 668.localhost.mene.ro"\
    "getent hosts 669.localhost.mene.ro"\
    "getent hosts 670.localhost.mene.ro"\
    "getent hosts 671.localhost.mene.ro"\
    "getent hosts 672.localhost.mene.ro"\
    "getent hosts 673.localhost.mene.ro"\
    "getent hosts 674.localhost.mene.ro"\
    "getent hosts 675.localhost.mene.ro"\
    "getent hosts 676.localhost.mene.ro"\
    "getent hosts 677.localhost.mene.ro"\
    "getent hosts 678.localhost.mene.ro"\
    "getent hosts 679.localhost.mene.ro"\
    "getent hosts 680.localhost.mene.ro"\
    "getent hosts 681.localhost.mene.ro"\
    "getent hosts 682.localhost.mene.ro"\
    "getent hosts 683.localhost.mene.ro"\
    "getent hosts 684.localhost.mene.ro"\
    "getent hosts 685.localhost.mene.ro"\
    "getent hosts 686.localhost.mene.ro"\
    "getent hosts 687.localhost.mene.ro"\
    "getent hosts 688.localhost.mene.ro"\
    "getent hosts 689.localhost.mene.ro"\
    "getent hosts 690.localhost.mene.ro"\
    "getent hosts 691.localhost.mene.ro"\
    "getent hosts 692.localhost.mene.ro"\
    "getent hosts 693.localhost.mene.ro"\
    "getent hosts 694.localhost.mene.ro"\
    "getent hosts 695.localhost.mene.ro"\
    "getent hosts 696.localhost.mene.ro"\
    "getent hosts 697.localhost.mene.ro"\
    "getent hosts 698.localhost.mene.ro"\
    "getent hosts 699.localhost.mene.ro"\
    "getent hosts 700.localhost.mene.ro"\
    "getent hosts 701.localhost.mene.ro"\
    "getent hosts 702.localhost.mene.ro"\
    "getent hosts 703.localhost.mene.ro"\
    "getent hosts 704.localhost.mene.ro"\
    "getent hosts 705.localhost.mene.ro"\
    "getent hosts 706.localhost.mene.ro"\
    "getent hosts 707.localhost.mene.ro"\
    "getent hosts 708.localhost.mene.ro"\
    "getent hosts 709.localhost.mene.ro"\
    "getent hosts 710.localhost.mene.ro"\
    "getent hosts 711.localhost.mene.ro"\
    "getent hosts 712.localhost.mene.ro"\
    "getent hosts 713.localhost.mene.ro"\
    "getent hosts 714.localhost.mene.ro"\
    "getent hosts 715.localhost.mene.ro"\
    "getent hosts 716.localhost.mene.ro"\
    "getent hosts 717.localhost.mene.ro"\
    "getent hosts 718.localhost.mene.ro"\
    "getent hosts 719.localhost.mene.ro"\
    "getent hosts 720.localhost.mene.ro"\
    "getent hosts 721.localhost.mene.ro"\
    "getent hosts 722.localhost.mene.ro"\
    "getent hosts 723.localhost.mene.ro"\
    "getent hosts 724.localhost.mene.ro"\
    "getent hosts 725.localhost.mene.ro"\
    "getent hosts 726.localhost.mene.ro"\
    "getent hosts 727.localhost.mene.ro"\
    "getent hosts 728.localhost.mene.ro"\
    "getent hosts 729.localhost.mene.ro"\
    "getent hosts 730.localhost.mene.ro"\
    "getent hosts 731.localhost.mene.ro"\
    "getent hosts 732.localhost.mene.ro"\
    "getent hosts 733.localhost.mene.ro"\
    "getent hosts 734.localhost.mene.ro"\
    "getent hosts 735.localhost.mene.ro"\
    "getent hosts 736.localhost.mene.ro"\
    "getent hosts 737.localhost.mene.ro"\
    "getent hosts 738.localhost.mene.ro"\
    "getent hosts 739.localhost.mene.ro"\
    "getent hosts 740.localhost.mene.ro"\
    "getent hosts 741.localhost.mene.ro"\
    "getent hosts 742.localhost.mene.ro"\
    "getent hosts 743.localhost.mene.ro"\
    "getent hosts 744.localhost.mene.ro"\
    "getent hosts 745.localhost.mene.ro"\
    "getent hosts 746.localhost.mene.ro"\
    "getent hosts 747.localhost.mene.ro"\
    "getent hosts 748.localhost.mene.ro"\
    "getent hosts 749.localhost.mene.ro"\
    "getent hosts 750.localhost.mene.ro"\
    "getent hosts 751.localhost.mene.ro"\
    "getent hosts 752.localhost.mene.ro"\
    "getent hosts 753.localhost.mene.ro"\
    "getent hosts 754.localhost.mene.ro"\
    "getent hosts 755.localhost.mene.ro"\
    "getent hosts 756.localhost.mene.ro"\
    "getent hosts 757.localhost.mene.ro"\
    "getent hosts 758.localhost.mene.ro"\
    "getent hosts 759.localhost.mene.ro"\
    "getent hosts 760.localhost.mene.ro"\
    "getent hosts 761.localhost.mene.ro"\
    "getent hosts 762.localhost.mene.ro"\
    "getent hosts 763.localhost.mene.ro"\
    "getent hosts 764.localhost.mene.ro"\
    "getent hosts 765.localhost.mene.ro"\
    "getent hosts 766.localhost.mene.ro"\
    "getent hosts 767.localhost.mene.ro"\
    "getent hosts 768.localhost.mene.ro"\
    "getent hosts 769.localhost.mene.ro"\
    "getent hosts 770.localhost.mene.ro"\
    "getent hosts 771.localhost.mene.ro"\
    "getent hosts 772.localhost.mene.ro"\
    "getent hosts 773.localhost.mene.ro"\
    "getent hosts 774.localhost.mene.ro"\
    "getent hosts 775.localhost.mene.ro"\
    "getent hosts 776.localhost.mene.ro"\
    "getent hosts 777.localhost.mene.ro"\
    "getent hosts 778.localhost.mene.ro"\
    "getent hosts 779.localhost.mene.ro"\
    "getent hosts 780.localhost.mene.ro"\
    "getent hosts 781.localhost.mene.ro"\
    "getent hosts 782.localhost.mene.ro"\
    "getent hosts 783.localhost.mene.ro"\
    "getent hosts 784.localhost.mene.ro"\
    "getent hosts 785.localhost.mene.ro"\
    "getent hosts 786.localhost.mene.ro"\
    "getent hosts 787.localhost.mene.ro"\
    "getent hosts 788.localhost.mene.ro"\
    "getent hosts 789.localhost.mene.ro"\
    "getent hosts 790.localhost.mene.ro"\
    "getent hosts 791.localhost.mene.ro"\
    "getent hosts 792.localhost.mene.ro"\
    "getent hosts 793.localhost.mene.ro"\
    "getent hosts 794.localhost.mene.ro"\
    "getent hosts 795.localhost.mene.ro"\
    "getent hosts 796.localhost.mene.ro"\
    "getent hosts 797.localhost.mene.ro"\
    "getent hosts 798.localhost.mene.ro"\
    "getent hosts 799.localhost.mene.ro"\
    "getent hosts 800.localhost.mene.ro"\
    "getent hosts 801.localhost.mene.ro"\
    "getent hosts 802.localhost.mene.ro"\
    "getent hosts 803.localhost.mene.ro"\
    "getent hosts 804.localhost.mene.ro"\
    "getent hosts 805.localhost.mene.ro"\
    "getent hosts 806.localhost.mene.ro"\
    "getent hosts 807.localhost.mene.ro"\
    "getent hosts 808.localhost.mene.ro"\
    "getent hosts 809.localhost.mene.ro"\
    "getent hosts 810.localhost.mene.ro"\
    "getent hosts 811.localhost.mene.ro"\
    "getent hosts 812.localhost.mene.ro"\
    "getent hosts 813.localhost.mene.ro"\
    "getent hosts 814.localhost.mene.ro"\
    "getent hosts 815.localhost.mene.ro"\
    "getent hosts 816.localhost.mene.ro"\
    "getent hosts 817.localhost.mene.ro"\
    "getent hosts 818.localhost.mene.ro"\
    "getent hosts 819.localhost.mene.ro"\
    "getent hosts 820.localhost.mene.ro"\
    "getent hosts 821.localhost.mene.ro"\
    "getent hosts 822.localhost.mene.ro"\
    "getent hosts 823.localhost.mene.ro"\
    "getent hosts 824.localhost.mene.ro"\
    "getent hosts 825.localhost.mene.ro"\
    "getent hosts 826.localhost.mene.ro"\
    "getent hosts 827.localhost.mene.ro"\
    "getent hosts 828.localhost.mene.ro"\
    "getent hosts 829.localhost.mene.ro"\
    "getent hosts 830.localhost.mene.ro"\
    "getent hosts 831.localhost.mene.ro"\
    "getent hosts 832.localhost.mene.ro"\
    "getent hosts 833.localhost.mene.ro"\
    "getent hosts 834.localhost.mene.ro"\
    "getent hosts 835.localhost.mene.ro"\
    "getent hosts 836.localhost.mene.ro"\
    "getent hosts 837.localhost.mene.ro"\
    "getent hosts 838.localhost.mene.ro"\
    "getent hosts 839.localhost.mene.ro"\
    "getent hosts 840.localhost.mene.ro"\
    "getent hosts 841.localhost.mene.ro"\
    "getent hosts 842.localhost.mene.ro"\
    "getent hosts 843.localhost.mene.ro"\
    "getent hosts 844.localhost.mene.ro"\
    "getent hosts 845.localhost.mene.ro"\
    "getent hosts 846.localhost.mene.ro"\
    "getent hosts 847.localhost.mene.ro"\
    "getent hosts 848.localhost.mene.ro"\
    "getent hosts 849.localhost.mene.ro"\
    "getent hosts 850.localhost.mene.ro"\
    "getent hosts 851.localhost.mene.ro"\
    "getent hosts 852.localhost.mene.ro"\
    "getent hosts 853.localhost.mene.ro"\
    "getent hosts 854.localhost.mene.ro"\
    "getent hosts 855.localhost.mene.ro"\
    "getent hosts 856.localhost.mene.ro"\
    "getent hosts 857.localhost.mene.ro"\
    "getent hosts 858.localhost.mene.ro"\
    "getent hosts 859.localhost.mene.ro"\
    "getent hosts 860.localhost.mene.ro"\
    "getent hosts 861.localhost.mene.ro"\
    "getent hosts 862.localhost.mene.ro"\
    "getent hosts 863.localhost.mene.ro"\
    "getent hosts 864.localhost.mene.ro"\
    "getent hosts 865.localhost.mene.ro"\
    "getent hosts 866.localhost.mene.ro"\
    "getent hosts 867.localhost.mene.ro"\
    "getent hosts 868.localhost.mene.ro"\
    "getent hosts 869.localhost.mene.ro"\
    "getent hosts 870.localhost.mene.ro"\
    "getent hosts 871.localhost.mene.ro"\
    "getent hosts 872.localhost.mene.ro"\
    "getent hosts 873.localhost.mene.ro"\
    "getent hosts 874.localhost.mene.ro"\
    "getent hosts 875.localhost.mene.ro"\
    "getent hosts 876.localhost.mene.ro"\
    "getent hosts 877.localhost.mene.ro"\
    "getent hosts 878.localhost.mene.ro"\
    "getent hosts 879.localhost.mene.ro"\
    "getent hosts 880.localhost.mene.ro"\
    "getent hosts 881.localhost.mene.ro"\
    "getent hosts 882.localhost.mene.ro"\
    "getent hosts 883.localhost.mene.ro"\
    "getent hosts 884.localhost.mene.ro"\
    "getent hosts 885.localhost.mene.ro"\
    "getent hosts 886.localhost.mene.ro"\
    "getent hosts 887.localhost.mene.ro"\
    "getent hosts 888.localhost.mene.ro"\
    "getent hosts 889.localhost.mene.ro"\
    "getent hosts 890.localhost.mene.ro"\
    "getent hosts 891.localhost.mene.ro"\
    "getent hosts 892.localhost.mene.ro"\
    "getent hosts 893.localhost.mene.ro"\
    "getent hosts 894.localhost.mene.ro"\
    "getent hosts 895.localhost.mene.ro"\
    "getent hosts 896.localhost.mene.ro"\
    "getent hosts 897.localhost.mene.ro"\
    "getent hosts 898.localhost.mene.ro"\
    "getent hosts 899.localhost.mene.ro"\
    "getent hosts 900.localhost.mene.ro"\
    "getent hosts 901.localhost.mene.ro"\
    "getent hosts 902.localhost.mene.ro"\
    "getent hosts 903.localhost.mene.ro"\
    "getent hosts 904.localhost.mene.ro"\
    "getent hosts 905.localhost.mene.ro"\
    "getent hosts 906.localhost.mene.ro"\
    "getent hosts 907.localhost.mene.ro"\
    "getent hosts 908.localhost.mene.ro"\
    "getent hosts 909.localhost.mene.ro"\
    "getent hosts 910.localhost.mene.ro"\
    "getent hosts 911.localhost.mene.ro"\
    "getent hosts 912.localhost.mene.ro"\
    "getent hosts 913.localhost.mene.ro"\
    "getent hosts 914.localhost.mene.ro"\
    "getent hosts 915.localhost.mene.ro"\
    "getent hosts 916.localhost.mene.ro"\
    "getent hosts 917.localhost.mene.ro"\
    "getent hosts 918.localhost.mene.ro"\
    "getent hosts 919.localhost.mene.ro"\
    "getent hosts 920.localhost.mene.ro"\
    "getent hosts 921.localhost.mene.ro"\
    "getent hosts 922.localhost.mene.ro"\
    "getent hosts 923.localhost.mene.ro"\
    "getent hosts 924.localhost.mene.ro"\
    "getent hosts 925.localhost.mene.ro"\
    "getent hosts 926.localhost.mene.ro"\
    "getent hosts 927.localhost.mene.ro"\
    "getent hosts 928.localhost.mene.ro"\
    "getent hosts 929.localhost.mene.ro"\
    "getent hosts 930.localhost.mene.ro"\
    "getent hosts 931.localhost.mene.ro"\
    "getent hosts 932.localhost.mene.ro"\
    "getent hosts 933.localhost.mene.ro"\
    "getent hosts 934.localhost.mene.ro"\
    "getent hosts 935.localhost.mene.ro"\
    "getent hosts 936.localhost.mene.ro"\
    "getent hosts 937.localhost.mene.ro"\
    "getent hosts 938.localhost.mene.ro"\
    "getent hosts 939.localhost.mene.ro"\
    "getent hosts 940.localhost.mene.ro"\
    "getent hosts 941.localhost.mene.ro"\
    "getent hosts 942.localhost.mene.ro"\
    "getent hosts 943.localhost.mene.ro"\
    "getent hosts 944.localhost.mene.ro"\
    "getent hosts 945.localhost.mene.ro"\
    "getent hosts 946.localhost.mene.ro"\
    "getent hosts 947.localhost.mene.ro"\
    "getent hosts 948.localhost.mene.ro"\
    "getent hosts 949.localhost.mene.ro"\
    "getent hosts 950.localhost.mene.ro"\
    "getent hosts 951.localhost.mene.ro"\
    "getent hosts 952.localhost.mene.ro"\
    "getent hosts 953.localhost.mene.ro"\
    "getent hosts 954.localhost.mene.ro"\
    "getent hosts 955.localhost.mene.ro"\
    "getent hosts 956.localhost.mene.ro"\
    "getent hosts 957.localhost.mene.ro"\
    "getent hosts 958.localhost.mene.ro"\
    "getent hosts 959.localhost.mene.ro"\
    "getent hosts 960.localhost.mene.ro"\
    "getent hosts 961.localhost.mene.ro"\
    "getent hosts 962.localhost.mene.ro"\
    "getent hosts 963.localhost.mene.ro"\
    "getent hosts 964.localhost.mene.ro"\
    "getent hosts 965.localhost.mene.ro"\
    "getent hosts 966.localhost.mene.ro"\
    "getent hosts 967.localhost.mene.ro"\
    "getent hosts 968.localhost.mene.ro"\
    "getent hosts 969.localhost.mene.ro"\
    "getent hosts 970.localhost.mene.ro"\
    "getent hosts 971.localhost.mene.ro"\
    "getent hosts 972.localhost.mene.ro"\
    "getent hosts 973.localhost.mene.ro"\
    "getent hosts 974.localhost.mene.ro"\
    "getent hosts 975.localhost.mene.ro"\
    "getent hosts 976.localhost.mene.ro"\
    "getent hosts 977.localhost.mene.ro"\
    "getent hosts 978.localhost.mene.ro"\
    "getent hosts 979.localhost.mene.ro"\
    "getent hosts 980.localhost.mene.ro"\
    "getent hosts 981.localhost.mene.ro"\
    "getent hosts 982.localhost.mene.ro"\
    "getent hosts 983.localhost.mene.ro"\
    "getent hosts 984.localhost.mene.ro"\
    "getent hosts 985.localhost.mene.ro"\
    "getent hosts 986.localhost.mene.ro"\
    "getent hosts 987.localhost.mene.ro"\
    "getent hosts 988.localhost.mene.ro"\
    "getent hosts 989.localhost.mene.ro"\
    "getent hosts 990.localhost.mene.ro"\
    "getent hosts 991.localhost.mene.ro"\
    "getent hosts 992.localhost.mene.ro"\
    "getent hosts 993.localhost.mene.ro"\
    "getent hosts 994.localhost.mene.ro"\
    "getent hosts 995.localhost.mene.ro"\
    "getent hosts 996.localhost.mene.ro"\
    "getent hosts 997.localhost.mene.ro"\
    "getent hosts 998.localhost.mene.ro"\
    "getent hosts 999.localhost.mene.ro"\
    "getent hosts 1000.localhost.mene.ro"\
    "getent hosts 1001.localhost.mene.ro"\
    "getent hosts 1002.localhost.mene.ro"\
    "getent hosts 1003.localhost.mene.ro"\
    "getent hosts 1004.localhost.mene.ro"\
    "getent hosts 1005.localhost.mene.ro"\
    "getent hosts 1006.localhost.mene.ro"\
    "getent hosts 1007.localhost.mene.ro"\
    "getent hosts 1008.localhost.mene.ro"\
    "getent hosts 1009.localhost.mene.ro"\
    "getent hosts 1010.localhost.mene.ro"\
    "getent hosts 1011.localhost.mene.ro"\
    "getent hosts 1012.localhost.mene.ro"\
    "getent hosts 1013.localhost.mene.ro"\
    "getent hosts 1014.localhost.mene.ro"\
    "getent hosts 1015.localhost.mene.ro"\
    "getent hosts 1016.localhost.mene.ro"\
    "getent hosts 1017.localhost.mene.ro"\
    "getent hosts 1018.localhost.mene.ro"\
    "getent hosts 1019.localhost.mene.ro"\
    "getent hosts 1020.localhost.mene.ro"\
    "getent hosts 1021.localhost.mene.ro"\
    "getent hosts 1022.localhost.mene.ro"\
    "getent hosts 1023.localhost.mene.ro"\
    "getent hosts 1024.localhost.mene.ro"\
    "getent hosts 1025.localhost.mene.ro"\
    "getent hosts 1026.localhost.mene.ro"\
    "getent hosts 1027.localhost.mene.ro"\
    "getent hosts 1028.localhost.mene.ro"\
    "getent hosts 1029.localhost.mene.ro"\
    "getent hosts 1030.localhost.mene.ro"\
    "getent hosts 1031.localhost.mene.ro"\
    "getent hosts 1032.localhost.mene.ro"\
    "getent hosts 1033.localhost.mene.ro"\
    "getent hosts 1034.localhost.mene.ro"\
    "getent hosts 1035.localhost.mene.ro"\
    "getent hosts 1036.localhost.mene.ro"\
    "getent hosts 1037.localhost.mene.ro"\
    "getent hosts 1038.localhost.mene.ro"\
    "getent hosts 1039.localhost.mene.ro"\
    "getent hosts 1040.localhost.mene.ro"\
    "getent hosts 1041.localhost.mene.ro"\
    "getent hosts 1042.localhost.mene.ro"\
    "getent hosts 1043.localhost.mene.ro"\
    "getent hosts 1044.localhost.mene.ro"\
    "getent hosts 1045.localhost.mene.ro"\
    "getent hosts 1046.localhost.mene.ro"\
    "getent hosts 1047.localhost.mene.ro"\
    "getent hosts 1048.localhost.mene.ro"\
    "getent hosts 1049.localhost.mene.ro"\
    "getent hosts 1050.localhost.mene.ro"\
    "getent hosts 1051.localhost.mene.ro"\
    "getent hosts 1052.localhost.mene.ro"\
    "getent hosts 1053.localhost.mene.ro"\
    "getent hosts 1054.localhost.mene.ro"\
    "getent hosts 1055.localhost.mene.ro"\
    "getent hosts 1056.localhost.mene.ro"\
    "getent hosts 1057.localhost.mene.ro"\
    "getent hosts 1058.localhost.mene.ro"\
    "getent hosts 1059.localhost.mene.ro"\
    "getent hosts 1060.localhost.mene.ro"\
    "getent hosts 1061.localhost.mene.ro"\
    "getent hosts 1062.localhost.mene.ro"\
    "getent hosts 1063.localhost.mene.ro"\
    "getent hosts 1064.localhost.mene.ro"\
    "getent hosts 1065.localhost.mene.ro"\
    "getent hosts 1066.localhost.mene.ro"\
    "getent hosts 1067.localhost.mene.ro"\
    "getent hosts 1068.localhost.mene.ro"\
    "getent hosts 1069.localhost.mene.ro"\
    "getent hosts 1070.localhost.mene.ro"\
    "getent hosts 1071.localhost.mene.ro"\
    "getent hosts 1072.localhost.mene.ro"\
    "getent hosts 1073.localhost.mene.ro"\
    "getent hosts 1074.localhost.mene.ro"\
    "getent hosts 1075.localhost.mene.ro"\
    "getent hosts 1076.localhost.mene.ro"\
    "getent hosts 1077.localhost.mene.ro"\
    "getent hosts 1078.localhost.mene.ro"\
    "getent hosts 1079.localhost.mene.ro"\
    "getent hosts 1080.localhost.mene.ro"\
    "getent hosts 1081.localhost.mene.ro"\
    "getent hosts 1082.localhost.mene.ro"\
    "getent hosts 1083.localhost.mene.ro"\
    "getent hosts 1084.localhost.mene.ro"\
    "getent hosts 1085.localhost.mene.ro"\
    "getent hosts 1086.localhost.mene.ro"\
    "getent hosts 1087.localhost.mene.ro"\
    "getent hosts 1088.localhost.mene.ro"\
    "getent hosts 1089.localhost.mene.ro"\
    "getent hosts 1090.localhost.mene.ro"\
    "getent hosts 1091.localhost.mene.ro"\
    "getent hosts 1092.localhost.mene.ro"\
    "getent hosts 1093.localhost.mene.ro"\
    "getent hosts 1094.localhost.mene.ro"\
    "getent hosts 1095.localhost.mene.ro"\
    "getent hosts 1096.localhost.mene.ro"\
    "getent hosts 1097.localhost.mene.ro"\
    "getent hosts 1098.localhost.mene.ro"\
    "getent hosts 1099.localhost.mene.ro"\
    "getent hosts 1100.localhost.mene.ro"\
    "getent hosts 1101.localhost.mene.ro"\
    "getent hosts 1102.localhost.mene.ro"\
    "getent hosts 1103.localhost.mene.ro"\
    "getent hosts 1104.localhost.mene.ro"\
    "getent hosts 1105.localhost.mene.ro"\
    "getent hosts 1106.localhost.mene.ro"\
    "getent hosts 1107.localhost.mene.ro"\
    "getent hosts 1108.localhost.mene.ro"\
    "getent hosts 1109.localhost.mene.ro"\
    "getent hosts 1110.localhost.mene.ro"\
    "getent hosts 1111.localhost.mene.ro"\
    "getent hosts 1112.localhost.mene.ro"\
    "getent hosts 1113.localhost.mene.ro"\
    "getent hosts 1114.localhost.mene.ro"\
    "getent hosts 1115.localhost.mene.ro"\
    "getent hosts 1116.localhost.mene.ro"\
    "getent hosts 1117.localhost.mene.ro"\
    "getent hosts 1118.localhost.mene.ro"\
    "getent hosts 1119.localhost.mene.ro"\
    "getent hosts 1120.localhost.mene.ro"\
    "getent hosts 1121.localhost.mene.ro"\
    "getent hosts 1122.localhost.mene.ro"\
    "getent hosts 1123.localhost.mene.ro"\
    "getent hosts 1124.localhost.mene.ro"\
    "getent hosts 1125.localhost.mene.ro"\
    "getent hosts 1126.localhost.mene.ro"\
    "getent hosts 1127.localhost.mene.ro"\
    "getent hosts 1128.localhost.mene.ro"\
    "getent hosts 1129.localhost.mene.ro"\
    "getent hosts 1130.localhost.mene.ro"\
    "getent hosts 1131.localhost.mene.ro"\
    "getent hosts 1132.localhost.mene.ro"\
    "getent hosts 1133.localhost.mene.ro"\
    "getent hosts 1134.localhost.mene.ro"\
    "getent hosts 1135.localhost.mene.ro"\
    "getent hosts 1136.localhost.mene.ro"\
    "getent hosts 1137.localhost.mene.ro"\
    "getent hosts 1138.localhost.mene.ro"\
    "getent hosts 1139.localhost.mene.ro"\
    "getent hosts 1140.localhost.mene.ro"\
    "getent hosts 1141.localhost.mene.ro"\
    "getent hosts 1142.localhost.mene.ro"\
    "getent hosts 1143.localhost.mene.ro"\
    "getent hosts 1144.localhost.mene.ro"\
    "getent hosts 1145.localhost.mene.ro"\
    "getent hosts 1146.localhost.mene.ro"\
    "getent hosts 1147.localhost.mene.ro"\
    "getent hosts 1148.localhost.mene.ro"\
    "getent hosts 1149.localhost.mene.ro"\
    "getent hosts 1150.localhost.mene.ro"\
    "getent hosts 1151.localhost.mene.ro"\
    "getent hosts 1152.localhost.mene.ro"\
    "getent hosts 1153.localhost.mene.ro"\
    "getent hosts 1154.localhost.mene.ro"\
    "getent hosts 1155.localhost.mene.ro"\
    "getent hosts 1156.localhost.mene.ro"\
    "getent hosts 1157.localhost.mene.ro"\
    "getent hosts 1158.localhost.mene.ro"\
    "getent hosts 1159.localhost.mene.ro"\
    "getent hosts 1160.localhost.mene.ro"\
    "getent hosts 1161.localhost.mene.ro"\
    "getent hosts 1162.localhost.mene.ro"\
    "getent hosts 1163.localhost.mene.ro"\
    "getent hosts 1164.localhost.mene.ro"\
    "getent hosts 1165.localhost.mene.ro"\
    "getent hosts 1166.localhost.mene.ro"\
    "getent hosts 1167.localhost.mene.ro"\
    "getent hosts 1168.localhost.mene.ro"\
    "getent hosts 1169.localhost.mene.ro"\
    "getent hosts 1170.localhost.mene.ro"\
    "getent hosts 1171.localhost.mene.ro"\
    "getent hosts 1172.localhost.mene.ro"\
    "getent hosts 1173.localhost.mene.ro"\
    "getent hosts 1174.localhost.mene.ro"\
    "getent hosts 1175.localhost.mene.ro"\
    "getent hosts 1176.localhost.mene.ro"\
    "getent hosts 1177.localhost.mene.ro"\
    "getent hosts 1178.localhost.mene.ro"\
    "getent hosts 1179.localhost.mene.ro"\
    "getent hosts 1180.localhost.mene.ro"\
    "getent hosts 1181.localhost.mene.ro"\
    "getent hosts 1182.localhost.mene.ro"\
    "getent hosts 1183.localhost.mene.ro"\
    "getent hosts 1184.localhost.mene.ro"\
    "getent hosts 1185.localhost.mene.ro"\
    "getent hosts 1186.localhost.mene.ro"\
    "getent hosts 1187.localhost.mene.ro"\
    "getent hosts 1188.localhost.mene.ro"\
    "getent hosts 1189.localhost.mene.ro"\
    "getent hosts 1190.localhost.mene.ro"\
    "getent hosts 1191.localhost.mene.ro"\
    "getent hosts 1192.localhost.mene.ro"\
    "getent hosts 1193.localhost.mene.ro"\
    "getent hosts 1194.localhost.mene.ro"\
    "getent hosts 1195.localhost.mene.ro"\
    "getent hosts 1196.localhost.mene.ro"\
    "getent hosts 1197.localhost.mene.ro"\
    "getent hosts 1198.localhost.mene.ro"\
    "getent hosts 1199.localhost.mene.ro"\
    "getent hosts 1200.localhost.mene.ro"\
    "getent hosts 1201.localhost.mene.ro"\
    "getent hosts 1202.localhost.mene.ro"\
    "getent hosts 1203.localhost.mene.ro"\
    "getent hosts 1204.localhost.mene.ro"\
    "getent hosts 1205.localhost.mene.ro"\
    "getent hosts 1206.localhost.mene.ro"\
    "getent hosts 1207.localhost.mene.ro"\
    "getent hosts 1208.localhost.mene.ro"\
    "getent hosts 1209.localhost.mene.ro"\
    "getent hosts 1210.localhost.mene.ro"\
    "getent hosts 1211.localhost.mene.ro"\
    "getent hosts 1212.localhost.mene.ro"\
    "getent hosts 1213.localhost.mene.ro"\
    "getent hosts 1214.localhost.mene.ro"\
    "getent hosts 1215.localhost.mene.ro"\
    "getent hosts 1216.localhost.mene.ro"\
    "getent hosts 1217.localhost.mene.ro"\
    "getent hosts 1218.localhost.mene.ro"\
    "getent hosts 1219.localhost.mene.ro"\
    "getent hosts 1220.localhost.mene.ro"\
    "getent hosts 1221.localhost.mene.ro"\
    "getent hosts 1222.localhost.mene.ro"\
    "getent hosts 1223.localhost.mene.ro"\
    "getent hosts 1224.localhost.mene.ro"\
    "getent hosts 1225.localhost.mene.ro"\
    "getent hosts 1226.localhost.mene.ro"\
    "getent hosts 1227.localhost.mene.ro"\
    "getent hosts 1228.localhost.mene.ro"\
    "getent hosts 1229.localhost.mene.ro"\
    "getent hosts 1230.localhost.mene.ro"\
    "getent hosts 1231.localhost.mene.ro"\
    "getent hosts 1232.localhost.mene.ro"\
    "getent hosts 1233.localhost.mene.ro"\
    "getent hosts 1234.localhost.mene.ro"\
    "getent hosts 1235.localhost.mene.ro"\
    "getent hosts 1236.localhost.mene.ro"\
    "getent hosts 1237.localhost.mene.ro"\
    "getent hosts 1238.localhost.mene.ro"\
    "getent hosts 1239.localhost.mene.ro"\
    "getent hosts 1240.localhost.mene.ro"\
    "getent hosts 1241.localhost.mene.ro"\
    "getent hosts 1242.localhost.mene.ro"\
    "getent hosts 1243.localhost.mene.ro"\
    "getent hosts 1244.localhost.mene.ro"\
    "getent hosts 1245.localhost.mene.ro"\
    "getent hosts 1246.localhost.mene.ro"\
    "getent hosts 1247.localhost.mene.ro"\
    "getent hosts 1248.localhost.mene.ro"\
    "getent hosts 1249.localhost.mene.ro"\
    "getent hosts 1250.localhost.mene.ro"\
    "getent hosts 1251.localhost.mene.ro"\
    "getent hosts 1252.localhost.mene.ro"\
    "getent hosts 1253.localhost.mene.ro"\
    "getent hosts 1254.localhost.mene.ro"\
    "getent hosts 1255.localhost.mene.ro"\
    "getent hosts 1256.localhost.mene.ro"\
    "getent hosts 1257.localhost.mene.ro"\
    "getent hosts 1258.localhost.mene.ro"\
    "getent hosts 1259.localhost.mene.ro"\
    "getent hosts 1260.localhost.mene.ro"\
    "getent hosts 1261.localhost.mene.ro"\
    "getent hosts 1262.localhost.mene.ro"\
    "getent hosts 1263.localhost.mene.ro"\
    "getent hosts 1264.localhost.mene.ro"\
    "getent hosts 1265.localhost.mene.ro"\
    "getent hosts 1266.localhost.mene.ro"\
    "getent hosts 1267.localhost.mene.ro"\
    "getent hosts 1268.localhost.mene.ro"\
    "getent hosts 1269.localhost.mene.ro"\
    "getent hosts 1270.localhost.mene.ro"\
    "getent hosts 1271.localhost.mene.ro"\
    "getent hosts 1272.localhost.mene.ro"\
    "getent hosts 1273.localhost.mene.ro"\
    "getent hosts 1274.localhost.mene.ro"\
    "getent hosts 1275.localhost.mene.ro"\
    "getent hosts 1276.localhost.mene.ro"\
    "getent hosts 1277.localhost.mene.ro"\
    "getent hosts 1278.localhost.mene.ro"\
    "getent hosts 1279.localhost.mene.ro"\
    "getent hosts 1280.localhost.mene.ro"\
    "getent hosts 1281.localhost.mene.ro"\
    "getent hosts 1282.localhost.mene.ro"\
    "getent hosts 1283.localhost.mene.ro"\
    "getent hosts 1284.localhost.mene.ro"\
    "getent hosts 1285.localhost.mene.ro"\
    "getent hosts 1286.localhost.mene.ro"\
    "getent hosts 1287.localhost.mene.ro"\
    "getent hosts 1288.localhost.mene.ro"\
    "getent hosts 1289.localhost.mene.ro"\
    "getent hosts 1290.localhost.mene.ro"\
    "getent hosts 1291.localhost.mene.ro"\
    "getent hosts 1292.localhost.mene.ro"\
    "getent hosts 1293.localhost.mene.ro"\
    "getent hosts 1294.localhost.mene.ro"\
    "getent hosts 1295.localhost.mene.ro"\
    "getent hosts 1296.localhost.mene.ro"\
    "getent hosts 1297.localhost.mene.ro"\
    "getent hosts 1298.localhost.mene.ro"\
    "getent hosts 1299.localhost.mene.ro"\
    "getent hosts 1300.localhost.mene.ro"\
    "getent hosts 1301.localhost.mene.ro"\
    "getent hosts 1302.localhost.mene.ro"\
    "getent hosts 1303.localhost.mene.ro"\
    "getent hosts 1304.localhost.mene.ro"\
    "getent hosts 1305.localhost.mene.ro"\
    "getent hosts 1306.localhost.mene.ro"\
    "getent hosts 1307.localhost.mene.ro"\
    "getent hosts 1308.localhost.mene.ro"\
    "getent hosts 1309.localhost.mene.ro"\
    "getent hosts 1310.localhost.mene.ro"\
    "getent hosts 1311.localhost.mene.ro"\
    "getent hosts 1312.localhost.mene.ro"\
    "getent hosts 1313.localhost.mene.ro"\
    "getent hosts 1314.localhost.mene.ro"\
    "getent hosts 1315.localhost.mene.ro"\
    "getent hosts 1316.localhost.mene.ro"\
    "getent hosts 1317.localhost.mene.ro"\
    "getent hosts 1318.localhost.mene.ro"\
    "getent hosts 1319.localhost.mene.ro"\
    "getent hosts 1320.localhost.mene.ro"\
    "getent hosts 1321.localhost.mene.ro"\
    "getent hosts 1322.localhost.mene.ro"\
    "getent hosts 1323.localhost.mene.ro"\
    "getent hosts 1324.localhost.mene.ro"\
    "getent hosts 1325.localhost.mene.ro"\
    "getent hosts 1326.localhost.mene.ro"\
    "getent hosts 1327.localhost.mene.ro"\
    "getent hosts 1328.localhost.mene.ro"\
    "getent hosts 1329.localhost.mene.ro"\
    "getent hosts 1330.localhost.mene.ro"\
    "getent hosts 1331.localhost.mene.ro"\
    "getent hosts 1332.localhost.mene.ro"\
    "getent hosts 1333.localhost.mene.ro"\
    "getent hosts 1334.localhost.mene.ro"\
    "getent hosts 1335.localhost.mene.ro"\
    "getent hosts 1336.localhost.mene.ro"\
    "getent hosts 1337.localhost.mene.ro"\
    "getent hosts 1338.localhost.mene.ro"\
    "getent hosts 1339.localhost.mene.ro"\
    "getent hosts 1340.localhost.mene.ro"\
    "getent hosts 1341.localhost.mene.ro"\
    "getent hosts 1342.localhost.mene.ro"\
    "getent hosts 1343.localhost.mene.ro"\
    "getent hosts 1344.localhost.mene.ro"\
    "getent hosts 1345.localhost.mene.ro"\
    "getent hosts 1346.localhost.mene.ro"\
    "getent hosts 1347.localhost.mene.ro"\
    "getent hosts 1348.localhost.mene.ro"\
    "getent hosts 1349.localhost.mene.ro"\
    "getent hosts 1350.localhost.mene.ro"\
    "getent hosts 1351.localhost.mene.ro"\
    "getent hosts 1352.localhost.mene.ro"\
    "getent hosts 1353.localhost.mene.ro"\
    "getent hosts 1354.localhost.mene.ro"\
    "getent hosts 1355.localhost.mene.ro"\
    "getent hosts 1356.localhost.mene.ro"\
    "getent hosts 1357.localhost.mene.ro"\
    "getent hosts 1358.localhost.mene.ro"\
    "getent hosts 1359.localhost.mene.ro"\
    "getent hosts 1360.localhost.mene.ro"\
    "getent hosts 1361.localhost.mene.ro"\
    "getent hosts 1362.localhost.mene.ro"\
    "getent hosts 1363.localhost.mene.ro"\
    "getent hosts 1364.localhost.mene.ro"\
    "getent hosts 1365.localhost.mene.ro"\
    "getent hosts 1366.localhost.mene.ro"\
    "getent hosts 1367.localhost.mene.ro"\
    "getent hosts 1368.localhost.mene.ro"\
    "getent hosts 1369.localhost.mene.ro"\
    "getent hosts 1370.localhost.mene.ro"\
    "getent hosts 1371.localhost.mene.ro"\
    "getent hosts 1372.localhost.mene.ro"\
    "getent hosts 1373.localhost.mene.ro"\
    "getent hosts 1374.localhost.mene.ro"\
    "getent hosts 1375.localhost.mene.ro"\
    "getent hosts 1376.localhost.mene.ro"\
    "getent hosts 1377.localhost.mene.ro"\
    "getent hosts 1378.localhost.mene.ro"\
    "getent hosts 1379.localhost.mene.ro"\
    "getent hosts 1380.localhost.mene.ro"\
    "getent hosts 1381.localhost.mene.ro"\
    "getent hosts 1382.localhost.mene.ro"\
    "getent hosts 1383.localhost.mene.ro"\
    "getent hosts 1384.localhost.mene.ro"\
    "getent hosts 1385.localhost.mene.ro"\
    "getent hosts 1386.localhost.mene.ro"\
    "getent hosts 1387.localhost.mene.ro"\
    "getent hosts 1388.localhost.mene.ro"\
    "getent hosts 1389.localhost.mene.ro"\
    "getent hosts 1390.localhost.mene.ro"\
    "getent hosts 1391.localhost.mene.ro"\
    "getent hosts 1392.localhost.mene.ro"\
    "getent hosts 1393.localhost.mene.ro"\
    "getent hosts 1394.localhost.mene.ro"\
    "getent hosts 1395.localhost.mene.ro"\
    "getent hosts 1396.localhost.mene.ro"\
    "getent hosts 1397.localhost.mene.ro"\
    "getent hosts 1398.localhost.mene.ro"\
    "getent hosts 1399.localhost.mene.ro"\
    "getent hosts 1400.localhost.mene.ro"\
    "getent hosts 1401.localhost.mene.ro"\
    "getent hosts 1402.localhost.mene.ro"\
    "getent hosts 1403.localhost.mene.ro"\
    "getent hosts 1404.localhost.mene.ro"\
    "getent hosts 1405.localhost.mene.ro"\
    "getent hosts 1406.localhost.mene.ro"\
    "getent hosts 1407.localhost.mene.ro"\
    "getent hosts 1408.localhost.mene.ro"\
    "getent hosts 1409.localhost.mene.ro"\
    "getent hosts 1410.localhost.mene.ro"\
    "getent hosts 1411.localhost.mene.ro"\
    "getent hosts 1412.localhost.mene.ro"\
    "getent hosts 1413.localhost.mene.ro"\
    "getent hosts 1414.localhost.mene.ro"\
    "getent hosts 1415.localhost.mene.ro"\
    "getent hosts 1416.localhost.mene.ro"\
    "getent hosts 1417.localhost.mene.ro"\
    "getent hosts 1418.localhost.mene.ro"\
    "getent hosts 1419.localhost.mene.ro"\
    "getent hosts 1420.localhost.mene.ro"\
    "getent hosts 1421.localhost.mene.ro"\
    "getent hosts 1422.localhost.mene.ro"\
    "getent hosts 1423.localhost.mene.ro"\
    "getent hosts 1424.localhost.mene.ro"\
    "getent hosts 1425.localhost.mene.ro"\
    "getent hosts 1426.localhost.mene.ro"\
    "getent hosts 1427.localhost.mene.ro"\
    "getent hosts 1428.localhost.mene.ro"\
    "getent hosts 1429.localhost.mene.ro"\
    "getent hosts 1430.localhost.mene.ro"\
    "getent hosts 1431.localhost.mene.ro"\
    "getent hosts 1432.localhost.mene.ro"\
    "getent hosts 1433.localhost.mene.ro"\
    "getent hosts 1434.localhost.mene.ro"\
    "getent hosts 1435.localhost.mene.ro"\
    "getent hosts 1436.localhost.mene.ro"\
    "getent hosts 1437.localhost.mene.ro"\
    "getent hosts 1438.localhost.mene.ro"\
    "getent hosts 1439.localhost.mene.ro"\
    "getent hosts 1440.localhost.mene.ro"\
    "getent hosts 1441.localhost.mene.ro"\
    "getent hosts 1442.localhost.mene.ro"\
    "getent hosts 1443.localhost.mene.ro"\
    "getent hosts 1444.localhost.mene.ro"\
    "getent hosts 1445.localhost.mene.ro"\
    "getent hosts 1446.localhost.mene.ro"\
    "getent hosts 1447.localhost.mene.ro"\
    "getent hosts 1448.localhost.mene.ro"\
    "getent hosts 1449.localhost.mene.ro"\
    "getent hosts 1450.localhost.mene.ro"\
    "getent hosts 1451.localhost.mene.ro"\
    "getent hosts 1452.localhost.mene.ro"\
    "getent hosts 1453.localhost.mene.ro"\
    "getent hosts 1454.localhost.mene.ro"\
    "getent hosts 1455.localhost.mene.ro"\
    "getent hosts 1456.localhost.mene.ro"\
    "getent hosts 1457.localhost.mene.ro"\
    "getent hosts 1458.localhost.mene.ro"\
    "getent hosts 1459.localhost.mene.ro"\
    "getent hosts 1460.localhost.mene.ro"\
    "getent hosts 1461.localhost.mene.ro"\
    "getent hosts 1462.localhost.mene.ro"\
    "getent hosts 1463.localhost.mene.ro"\
    "getent hosts 1464.localhost.mene.ro"\
    "getent hosts 1465.localhost.mene.ro"\
    "getent hosts 1466.localhost.mene.ro"\
    "getent hosts 1467.localhost.mene.ro"\
    "getent hosts 1468.localhost.mene.ro"\
    "getent hosts 1469.localhost.mene.ro"\
    "getent hosts 1470.localhost.mene.ro"\
    "getent hosts 1471.localhost.mene.ro"\
    "getent hosts 1472.localhost.mene.ro"\
    "getent hosts 1473.localhost.mene.ro"\
    "getent hosts 1474.localhost.mene.ro"\
    "getent hosts 1475.localhost.mene.ro"\
    "getent hosts 1476.localhost.mene.ro"\
    "getent hosts 1477.localhost.mene.ro"\
    "getent hosts 1478.localhost.mene.ro"\
    "getent hosts 1479.localhost.mene.ro"\
    "getent hosts 1480.localhost.mene.ro"\
    "getent hosts 1481.localhost.mene.ro"\
    "getent hosts 1482.localhost.mene.ro"\
    "getent hosts 1483.localhost.mene.ro"\
    "getent hosts 1484.localhost.mene.ro"\
    "getent hosts 1485.localhost.mene.ro"\
    "getent hosts 1486.localhost.mene.ro"\
    "getent hosts 1487.localhost.mene.ro"\
    "getent hosts 1488.localhost.mene.ro"\
    "getent hosts 1489.localhost.mene.ro"\
    "getent hosts 1490.localhost.mene.ro"\
    "getent hosts 1491.localhost.mene.ro"\
    "getent hosts 1492.localhost.mene.ro"\
    "getent hosts 1493.localhost.mene.ro"\
    "getent hosts 1494.localhost.mene.ro"\
    "getent hosts 1495.localhost.mene.ro"\
    "getent hosts 1496.localhost.mene.ro"\
    "getent hosts 1497.localhost.mene.ro"\
    "getent hosts 1498.localhost.mene.ro"\
    "getent hosts 1499.localhost.mene.ro"\
    "getent hosts 1500.localhost.mene.ro"\
    "getent hosts 1501.localhost.mene.ro"\
    "getent hosts 1502.localhost.mene.ro"\
    "getent hosts 1503.localhost.mene.ro"\
    "getent hosts 1504.localhost.mene.ro"\
    "getent hosts 1505.localhost.mene.ro"\
    "getent hosts 1506.localhost.mene.ro"\
    "getent hosts 1507.localhost.mene.ro"\
    "getent hosts 1508.localhost.mene.ro"\
    "getent hosts 1509.localhost.mene.ro"\
    "getent hosts 1510.localhost.mene.ro"\
    "getent hosts 1511.localhost.mene.ro"\
    "getent hosts 1512.localhost.mene.ro"\
    "getent hosts 1513.localhost.mene.ro"\
    "getent hosts 1514.localhost.mene.ro"\
    "getent hosts 1515.localhost.mene.ro"\
    "getent hosts 1516.localhost.mene.ro"\
    "getent hosts 1517.localhost.mene.ro"\
    "getent hosts 1518.localhost.mene.ro"\
    "getent hosts 1519.localhost.mene.ro"\
    "getent hosts 1520.localhost.mene.ro"\
    "getent hosts 1521.localhost.mene.ro"\
    "getent hosts 1522.localhost.mene.ro"\
    "getent hosts 1523.localhost.mene.ro"\
    "getent hosts 1524.localhost.mene.ro"\
    "getent hosts 1525.localhost.mene.ro"\
    "getent hosts 1526.localhost.mene.ro"\
    "getent hosts 1527.localhost.mene.ro"\
    "getent hosts 1528.localhost.mene.ro"\
    "getent hosts 1529.localhost.mene.ro"\
    "getent hosts 1530.localhost.mene.ro"\
    "getent hosts 1531.localhost.mene.ro"\
    "getent hosts 1532.localhost.mene.ro"\
    "getent hosts 1533.localhost.mene.ro"\
    "getent hosts 1534.localhost.mene.ro"\
    "getent hosts 1535.localhost.mene.ro"\
    "getent hosts 1536.localhost.mene.ro"\
    "getent hosts 1537.localhost.mene.ro"\
    "getent hosts 1538.localhost.mene.ro"\
    "getent hosts 1539.localhost.mene.ro"\
    "getent hosts 1540.localhost.mene.ro"\
    "getent hosts 1541.localhost.mene.ro"\
    "getent hosts 1542.localhost.mene.ro"\
    "getent hosts 1543.localhost.mene.ro"\
    "getent hosts 1544.localhost.mene.ro"\
    "getent hosts 1545.localhost.mene.ro"\
    "getent hosts 1546.localhost.mene.ro"\
    "getent hosts 1547.localhost.mene.ro"\
    "getent hosts 1548.localhost.mene.ro"\
    "getent hosts 1549.localhost.mene.ro"\
    "getent hosts 1550.localhost.mene.ro"\
    "getent hosts 1551.localhost.mene.ro"\
    "getent hosts 1552.localhost.mene.ro"\
    "getent hosts 1553.localhost.mene.ro"\
    "getent hosts 1554.localhost.mene.ro"\
    "getent hosts 1555.localhost.mene.ro"\
    "getent hosts 1556.localhost.mene.ro"\
    "getent hosts 1557.localhost.mene.ro"\
    "getent hosts 1558.localhost.mene.ro"\
    "getent hosts 1559.localhost.mene.ro"\
    "getent hosts 1560.localhost.mene.ro"\
    "getent hosts 1561.localhost.mene.ro"\
    "getent hosts 1562.localhost.mene.ro"\
    "getent hosts 1563.localhost.mene.ro"\
    "getent hosts 1564.localhost.mene.ro"\
    "getent hosts 1565.localhost.mene.ro"\
    "getent hosts 1566.localhost.mene.ro"\
    "getent hosts 1567.localhost.mene.ro"\
    "getent hosts 1568.localhost.mene.ro"\
    "getent hosts 1569.localhost.mene.ro"\
    "getent hosts 1570.localhost.mene.ro"\
    "getent hosts 1571.localhost.mene.ro"\
    "getent hosts 1572.localhost.mene.ro"\
    "getent hosts 1573.localhost.mene.ro"\
    "getent hosts 1574.localhost.mene.ro"\
    "getent hosts 1575.localhost.mene.ro"\
    "getent hosts 1576.localhost.mene.ro"\
    "getent hosts 1577.localhost.mene.ro"\
    "getent hosts 1578.localhost.mene.ro"\
    "getent hosts 1579.localhost.mene.ro"\
    "getent hosts 1580.localhost.mene.ro"\
    "getent hosts 1581.localhost.mene.ro"\
    "getent hosts 1582.localhost.mene.ro"\
    "getent hosts 1583.localhost.mene.ro"\
    "getent hosts 1584.localhost.mene.ro"\
    "getent hosts 1585.localhost.mene.ro"\
    "getent hosts 1586.localhost.mene.ro"\
    "getent hosts 1587.localhost.mene.ro"\
    "getent hosts 1588.localhost.mene.ro"\
    "getent hosts 1589.localhost.mene.ro"\
    "getent hosts 1590.localhost.mene.ro"\
    "getent hosts 1591.localhost.mene.ro"\
    "getent hosts 1592.localhost.mene.ro"\
    "getent hosts 1593.localhost.mene.ro"\
    "getent hosts 1594.localhost.mene.ro"\
    "getent hosts 1595.localhost.mene.ro"\
    "getent hosts 1596.localhost.mene.ro"\
    "getent hosts 1597.localhost.mene.ro"\
    "getent hosts 1598.localhost.mene.ro"\
    "getent hosts 1599.localhost.mene.ro"\
    "getent hosts 1600.localhost.mene.ro"\
    "getent hosts 1601.localhost.mene.ro"\
    "getent hosts 1602.localhost.mene.ro"\
    "getent hosts 1603.localhost.mene.ro"\
    "getent hosts 1604.localhost.mene.ro"\
    "getent hosts 1605.localhost.mene.ro"\
    "getent hosts 1606.localhost.mene.ro"\
    "getent hosts 1607.localhost.mene.ro"\
    "getent hosts 1608.localhost.mene.ro"\
    "getent hosts 1609.localhost.mene.ro"\
    "getent hosts 1610.localhost.mene.ro"\
    "getent hosts 1611.localhost.mene.ro"\
    "getent hosts 1612.localhost.mene.ro"\
    "getent hosts 1613.localhost.mene.ro"\
    "getent hosts 1614.localhost.mene.ro"\
    "getent hosts 1615.localhost.mene.ro"\
    "getent hosts 1616.localhost.mene.ro"\
    "getent hosts 1617.localhost.mene.ro"\
    "getent hosts 1618.localhost.mene.ro"\
    "getent hosts 1619.localhost.mene.ro"\
    "getent hosts 1620.localhost.mene.ro"\
    "getent hosts 1621.localhost.mene.ro"\
    "getent hosts 1622.localhost.mene.ro"\
    "getent hosts 1623.localhost.mene.ro"\
    "getent hosts 1624.localhost.mene.ro"\
    "getent hosts 1625.localhost.mene.ro"\
    "getent hosts 1626.localhost.mene.ro"\
    "getent hosts 1627.localhost.mene.ro"\
    "getent hosts 1628.localhost.mene.ro"\
    "getent hosts 1629.localhost.mene.ro"\
    "getent hosts 1630.localhost.mene.ro"\
    "getent hosts 1631.localhost.mene.ro"\
    "getent hosts 1632.localhost.mene.ro"\
    "getent hosts 1633.localhost.mene.ro"\
    "getent hosts 1634.localhost.mene.ro"\
    "getent hosts 1635.localhost.mene.ro"\
    "getent hosts 1636.localhost.mene.ro"\
    "getent hosts 1637.localhost.mene.ro"\
    "getent hosts 1638.localhost.mene.ro"\
    "getent hosts 1639.localhost.mene.ro"\
    "getent hosts 1640.localhost.mene.ro"\
    "getent hosts 1641.localhost.mene.ro"\
    "getent hosts 1642.localhost.mene.ro"\
    "getent hosts 1643.localhost.mene.ro"\
    "getent hosts 1644.localhost.mene.ro"\
    "getent hosts 1645.localhost.mene.ro"\
    "getent hosts 1646.localhost.mene.ro"\
    "getent hosts 1647.localhost.mene.ro"\
    "getent hosts 1648.localhost.mene.ro"\
    "getent hosts 1649.localhost.mene.ro"\
    "getent hosts 1650.localhost.mene.ro"\
    "getent hosts 1651.localhost.mene.ro"\
    "getent hosts 1652.localhost.mene.ro"\
    "getent hosts 1653.localhost.mene.ro"\
    "getent hosts 1654.localhost.mene.ro"\
    "getent hosts 1655.localhost.mene.ro"\
    "getent hosts 1656.localhost.mene.ro"\
    "getent hosts 1657.localhost.mene.ro"\
    "getent hosts 1658.localhost.mene.ro"\
    "getent hosts 1659.localhost.mene.ro"\
    "getent hosts 1660.localhost.mene.ro"\
    "getent hosts 1661.localhost.mene.ro"\
    "getent hosts 1662.localhost.mene.ro"\
    "getent hosts 1663.localhost.mene.ro"\
    "getent hosts 1664.localhost.mene.ro"\
    "getent hosts 1665.localhost.mene.ro"\
    "getent hosts 1666.localhost.mene.ro"\
    "getent hosts 1667.localhost.mene.ro"\
    "getent hosts 1668.localhost.mene.ro"\
    "getent hosts 1669.localhost.mene.ro"\
    "getent hosts 1670.localhost.mene.ro"\
    "getent hosts 1671.localhost.mene.ro"\
    "getent hosts 1672.localhost.mene.ro"\
    "getent hosts 1673.localhost.mene.ro"\
    "getent hosts 1674.localhost.mene.ro"\
    "getent hosts 1675.localhost.mene.ro"\
    "getent hosts 1676.localhost.mene.ro"\
    "getent hosts 1677.localhost.mene.ro"\
    "getent hosts 1678.localhost.mene.ro"\
    "getent hosts 1679.localhost.mene.ro"\
    "getent hosts 1680.localhost.mene.ro"\
    "getent hosts 1681.localhost.mene.ro"\
    "getent hosts 1682.localhost.mene.ro"\
    "getent hosts 1683.localhost.mene.ro"\
    "getent hosts 1684.localhost.mene.ro"\
    "getent hosts 1685.localhost.mene.ro"\
    "getent hosts 1686.localhost.mene.ro"\
    "getent hosts 1687.localhost.mene.ro"\
    "getent hosts 1688.localhost.mene.ro"\
    "getent hosts 1689.localhost.mene.ro"\
    "getent hosts 1690.localhost.mene.ro"\
    "getent hosts 1691.localhost.mene.ro"\
    "getent hosts 1692.localhost.mene.ro"\
    "getent hosts 1693.localhost.mene.ro"\
    "getent hosts 1694.localhost.mene.ro"\
    "getent hosts 1695.localhost.mene.ro"\
    "getent hosts 1696.localhost.mene.ro"\
    "getent hosts 1697.localhost.mene.ro"\
    "getent hosts 1698.localhost.mene.ro"\
    "getent hosts 1699.localhost.mene.ro"\
    "getent hosts 1700.localhost.mene.ro"\
    "getent hosts 1701.localhost.mene.ro"\
    "getent hosts 1702.localhost.mene.ro"\
    "getent hosts 1703.localhost.mene.ro"\
    "getent hosts 1704.localhost.mene.ro"\
    "getent hosts 1705.localhost.mene.ro"\
    "getent hosts 1706.localhost.mene.ro"\
    "getent hosts 1707.localhost.mene.ro"\
    "getent hosts 1708.localhost.mene.ro"\
    "getent hosts 1709.localhost.mene.ro"\
    "getent hosts 1710.localhost.mene.ro"\
    "getent hosts 1711.localhost.mene.ro"\
    "getent hosts 1712.localhost.mene.ro"\
    "getent hosts 1713.localhost.mene.ro"\
    "getent hosts 1714.localhost.mene.ro"\
    "getent hosts 1715.localhost.mene.ro"\
    "getent hosts 1716.localhost.mene.ro"\
    "getent hosts 1717.localhost.mene.ro"\
    "getent hosts 1718.localhost.mene.ro"\
    "getent hosts 1719.localhost.mene.ro"\
    "getent hosts 1720.localhost.mene.ro"\
    "getent hosts 1721.localhost.mene.ro"\
    "getent hosts 1722.localhost.mene.ro"\
    "getent hosts 1723.localhost.mene.ro"\
    "getent hosts 1724.localhost.mene.ro"\
    "getent hosts 1725.localhost.mene.ro"\
    "getent hosts 1726.localhost.mene.ro"\
    "getent hosts 1727.localhost.mene.ro"\
    "getent hosts 1728.localhost.mene.ro"\
    "getent hosts 1729.localhost.mene.ro"\
    "getent hosts 1730.localhost.mene.ro"\
    "getent hosts 1731.localhost.mene.ro"\
    "getent hosts 1732.localhost.mene.ro"\
    "getent hosts 1733.localhost.mene.ro"\
    "getent hosts 1734.localhost.mene.ro"\
    "getent hosts 1735.localhost.mene.ro"\
    "getent hosts 1736.localhost.mene.ro"\
    "getent hosts 1737.localhost.mene.ro"\
    "getent hosts 1738.localhost.mene.ro"\
    "getent hosts 1739.localhost.mene.ro"\
    "getent hosts 1740.localhost.mene.ro"\
    "getent hosts 1741.localhost.mene.ro"\
    "getent hosts 1742.localhost.mene.ro"\
    "getent hosts 1743.localhost.mene.ro"\
    "getent hosts 1744.localhost.mene.ro"\
    "getent hosts 1745.localhost.mene.ro"\
    "getent hosts 1746.localhost.mene.ro"\
    "getent hosts 1747.localhost.mene.ro"\
    "getent hosts 1748.localhost.mene.ro"\
    "getent hosts 1749.localhost.mene.ro"\
    "getent hosts 1750.localhost.mene.ro"\
    "getent hosts 1751.localhost.mene.ro"\
    "getent hosts 1752.localhost.mene.ro"\
    "getent hosts 1753.localhost.mene.ro"\
    "getent hosts 1754.localhost.mene.ro"\
    "getent hosts 1755.localhost.mene.ro"\
    "getent hosts 1756.localhost.mene.ro"\
    "getent hosts 1757.localhost.mene.ro"\
    "getent hosts 1758.localhost.mene.ro"\
    "getent hosts 1759.localhost.mene.ro"\
    "getent hosts 1760.localhost.mene.ro"\
    "getent hosts 1761.localhost.mene.ro"\
    "getent hosts 1762.localhost.mene.ro"\
    "getent hosts 1763.localhost.mene.ro"\
    "getent hosts 1764.localhost.mene.ro"\
    "getent hosts 1765.localhost.mene.ro"\
    "getent hosts 1766.localhost.mene.ro"\
    "getent hosts 1767.localhost.mene.ro"\
    "getent hosts 1768.localhost.mene.ro"\
    "getent hosts 1769.localhost.mene.ro"\
    "getent hosts 1770.localhost.mene.ro"\
    "getent hosts 1771.localhost.mene.ro"\
    "getent hosts 1772.localhost.mene.ro"\
    "getent hosts 1773.localhost.mene.ro"\
    "getent hosts 1774.localhost.mene.ro"\
    "getent hosts 1775.localhost.mene.ro"\
    "getent hosts 1776.localhost.mene.ro"\
    "getent hosts 1777.localhost.mene.ro"\
    "getent hosts 1778.localhost.mene.ro"\
    "getent hosts 1779.localhost.mene.ro"\
    "getent hosts 1780.localhost.mene.ro"\
    "getent hosts 1781.localhost.mene.ro"\
    "getent hosts 1782.localhost.mene.ro"\
    "getent hosts 1783.localhost.mene.ro"\
    "getent hosts 1784.localhost.mene.ro"\
    "getent hosts 1785.localhost.mene.ro"\
    "getent hosts 1786.localhost.mene.ro"\
    "getent hosts 1787.localhost.mene.ro"\
    "getent hosts 1788.localhost.mene.ro"\
    "getent hosts 1789.localhost.mene.ro"\
    "getent hosts 1790.localhost.mene.ro"\
    "getent hosts 1791.localhost.mene.ro"\
    "getent hosts 1792.localhost.mene.ro"\
    "getent hosts 1793.localhost.mene.ro"\
    "getent hosts 1794.localhost.mene.ro"\
    "getent hosts 1795.localhost.mene.ro"\
    "getent hosts 1796.localhost.mene.ro"\
    "getent hosts 1797.localhost.mene.ro"\
    "getent hosts 1798.localhost.mene.ro"\
    "getent hosts 1799.localhost.mene.ro"\
    "getent hosts 1800.localhost.mene.ro"\
    "getent hosts 1801.localhost.mene.ro"\
    "getent hosts 1802.localhost.mene.ro"\
    "getent hosts 1803.localhost.mene.ro"\
    "getent hosts 1804.localhost.mene.ro"\
    "getent hosts 1805.localhost.mene.ro"\
    "getent hosts 1806.localhost.mene.ro"\
    "getent hosts 1807.localhost.mene.ro"\
    "getent hosts 1808.localhost.mene.ro"\
    "getent hosts 1809.localhost.mene.ro"\
    "getent hosts 1810.localhost.mene.ro"\
    "getent hosts 1811.localhost.mene.ro"\
    "getent hosts 1812.localhost.mene.ro"\
    "getent hosts 1813.localhost.mene.ro"\
    "getent hosts 1814.localhost.mene.ro"\
    "getent hosts 1815.localhost.mene.ro"\
    "getent hosts 1816.localhost.mene.ro"\
    "getent hosts 1817.localhost.mene.ro"\
    "getent hosts 1818.localhost.mene.ro"\
    "getent hosts 1819.localhost.mene.ro"\
    "getent hosts 1820.localhost.mene.ro"\
    "getent hosts 1821.localhost.mene.ro"\
    "getent hosts 1822.localhost.mene.ro"\
    "getent hosts 1823.localhost.mene.ro"\
    "getent hosts 1824.localhost.mene.ro"\
    "getent hosts 1825.localhost.mene.ro"\
    "getent hosts 1826.localhost.mene.ro"\
    "getent hosts 1827.localhost.mene.ro"\
    "getent hosts 1828.localhost.mene.ro"\
    "getent hosts 1829.localhost.mene.ro"\
    "getent hosts 1830.localhost.mene.ro"\
    "getent hosts 1831.localhost.mene.ro"\
    "getent hosts 1832.localhost.mene.ro"\
    "getent hosts 1833.localhost.mene.ro"\
    "getent hosts 1834.localhost.mene.ro"\
    "getent hosts 1835.localhost.mene.ro"\
    "getent hosts 1836.localhost.mene.ro"\
    "getent hosts 1837.localhost.mene.ro"\
    "getent hosts 1838.localhost.mene.ro"\
    "getent hosts 1839.localhost.mene.ro"\
    "getent hosts 1840.localhost.mene.ro"\
    "getent hosts 1841.localhost.mene.ro"\
    "getent hosts 1842.localhost.mene.ro"\
    "getent hosts 1843.localhost.mene.ro"\
    "getent hosts 1844.localhost.mene.ro"\
    "getent hosts 1845.localhost.mene.ro"\
    "getent hosts 1846.localhost.mene.ro"\
    "getent hosts 1847.localhost.mene.ro"\
    "getent hosts 1848.localhost.mene.ro"\
    "getent hosts 1849.localhost.mene.ro"\
    "getent hosts 1850.localhost.mene.ro"\
    "getent hosts 1851.localhost.mene.ro"\
    "getent hosts 1852.localhost.mene.ro"\
    "getent hosts 1853.localhost.mene.ro"\
    "getent hosts 1854.localhost.mene.ro"\
    "getent hosts 1855.localhost.mene.ro"\
    "getent hosts 1856.localhost.mene.ro"\
    "getent hosts 1857.localhost.mene.ro"\
    "getent hosts 1858.localhost.mene.ro"\
    "getent hosts 1859.localhost.mene.ro"\
    "getent hosts 1860.localhost.mene.ro"\
    "getent hosts 1861.localhost.mene.ro"\
    "getent hosts 1862.localhost.mene.ro"\
    "getent hosts 1863.localhost.mene.ro"\
    "getent hosts 1864.localhost.mene.ro"\
    "getent hosts 1865.localhost.mene.ro"\
    "getent hosts 1866.localhost.mene.ro"\
    "getent hosts 1867.localhost.mene.ro"\
    "getent hosts 1868.localhost.mene.ro"\
    "getent hosts 1869.localhost.mene.ro"\
    "getent hosts 1870.localhost.mene.ro"\
    "getent hosts 1871.localhost.mene.ro"\
    "getent hosts 1872.localhost.mene.ro"\
    "getent hosts 1873.localhost.mene.ro"\
    "getent hosts 1874.localhost.mene.ro"\
    "getent hosts 1875.localhost.mene.ro"\
    "getent hosts 1876.localhost.mene.ro"\
    "getent hosts 1877.localhost.mene.ro"\
    "getent hosts 1878.localhost.mene.ro"\
    "getent hosts 1879.localhost.mene.ro"\
    "getent hosts 1880.localhost.mene.ro"\
    "getent hosts 1881.localhost.mene.ro"\
    "getent hosts 1882.localhost.mene.ro"\
    "getent hosts 1883.localhost.mene.ro"\
    "getent hosts 1884.localhost.mene.ro"\
    "getent hosts 1885.localhost.mene.ro"\
    "getent hosts 1886.localhost.mene.ro"\
    "getent hosts 1887.localhost.mene.ro"\
    "getent hosts 1888.localhost.mene.ro"\
    "getent hosts 1889.localhost.mene.ro"\
    "getent hosts 1890.localhost.mene.ro"\
    "getent hosts 1891.localhost.mene.ro"\
    "getent hosts 1892.localhost.mene.ro"\
    "getent hosts 1893.localhost.mene.ro"\
    "getent hosts 1894.localhost.mene.ro"\
    "getent hosts 1895.localhost.mene.ro"\
    "getent hosts 1896.localhost.mene.ro"\
    "getent hosts 1897.localhost.mene.ro"\
    "getent hosts 1898.localhost.mene.ro"\
    "getent hosts 1899.localhost.mene.ro"\
    "getent hosts 1900.localhost.mene.ro"\
    "getent hosts 1901.localhost.mene.ro"\
    "getent hosts 1902.localhost.mene.ro"\
    "getent hosts 1903.localhost.mene.ro"\
    "getent hosts 1904.localhost.mene.ro"\
    "getent hosts 1905.localhost.mene.ro"\
    "getent hosts 1906.localhost.mene.ro"\
    "getent hosts 1907.localhost.mene.ro"\
    "getent hosts 1908.localhost.mene.ro"\
    "getent hosts 1909.localhost.mene.ro"\
    "getent hosts 1910.localhost.mene.ro"\
    "getent hosts 1911.localhost.mene.ro"\
    "getent hosts 1912.localhost.mene.ro"\
    "getent hosts 1913.localhost.mene.ro"\
    "getent hosts 1914.localhost.mene.ro"\
    "getent hosts 1915.localhost.mene.ro"\
    "getent hosts 1916.localhost.mene.ro"\
    "getent hosts 1917.localhost.mene.ro"\
    "getent hosts 1918.localhost.mene.ro"\
    "getent hosts 1919.localhost.mene.ro"\
    "getent hosts 1920.localhost.mene.ro"\
    "getent hosts 1921.localhost.mene.ro"\
    "getent hosts 1922.localhost.mene.ro"\
    "getent hosts 1923.localhost.mene.ro"\
    "getent hosts 1924.localhost.mene.ro"\
    "getent hosts 1925.localhost.mene.ro"\
    "getent hosts 1926.localhost.mene.ro"\
    "getent hosts 1927.localhost.mene.ro"\
    "getent hosts 1928.localhost.mene.ro"\
    "getent hosts 1929.localhost.mene.ro"\
    "getent hosts 1930.localhost.mene.ro"\
    "getent hosts 1931.localhost.mene.ro"\
    "getent hosts 1932.localhost.mene.ro"\
    "getent hosts 1933.localhost.mene.ro"\
    "getent hosts 1934.localhost.mene.ro"\
    "getent hosts 1935.localhost.mene.ro"\
    "getent hosts 1936.localhost.mene.ro"\
    "getent hosts 1937.localhost.mene.ro"\
    "getent hosts 1938.localhost.mene.ro"\
    "getent hosts 1939.localhost.mene.ro"\
    "getent hosts 1940.localhost.mene.ro"\
    "getent hosts 1941.localhost.mene.ro"\
    "getent hosts 1942.localhost.mene.ro"\
    "getent hosts 1943.localhost.mene.ro"\
    "getent hosts 1944.localhost.mene.ro"\
    "getent hosts 1945.localhost.mene.ro"\
    "getent hosts 1946.localhost.mene.ro"\
    "getent hosts 1947.localhost.mene.ro"\
    "getent hosts 1948.localhost.mene.ro"\
    "getent hosts 1949.localhost.mene.ro"\
    "getent hosts 1950.localhost.mene.ro"\
    "getent hosts 1951.localhost.mene.ro"\
    "getent hosts 1952.localhost.mene.ro"\
    "getent hosts 1953.localhost.mene.ro"\
    "getent hosts 1954.localhost.mene.ro"\
    "getent hosts 1955.localhost.mene.ro"\
    "getent hosts 1956.localhost.mene.ro"\
    "getent hosts 1957.localhost.mene.ro"\
    "getent hosts 1958.localhost.mene.ro"\
    "getent hosts 1959.localhost.mene.ro"\
    "getent hosts 1960.localhost.mene.ro"\
    "getent hosts 1961.localhost.mene.ro"\
    "getent hosts 1962.localhost.mene.ro"\
    "getent hosts 1963.localhost.mene.ro"\
    "getent hosts 1964.localhost.mene.ro"\
    "getent hosts 1965.localhost.mene.ro"\
    "getent hosts 1966.localhost.mene.ro"\
    "getent hosts 1967.localhost.mene.ro"\
    "getent hosts 1968.localhost.mene.ro"\
    "getent hosts 1969.localhost.mene.ro"\
    "getent hosts 1970.localhost.mene.ro"\
    "getent hosts 1971.localhost.mene.ro"\
    "getent hosts 1972.localhost.mene.ro"\
    "getent hosts 1973.localhost.mene.ro"\
    "getent hosts 1974.localhost.mene.ro"\
    "getent hosts 1975.localhost.mene.ro"\
    "getent hosts 1976.localhost.mene.ro"\
    "getent hosts 1977.localhost.mene.ro"\
    "getent hosts 1978.localhost.mene.ro"\
    "getent hosts 1979.localhost.mene.ro"\
    "getent hosts 1980.localhost.mene.ro"\
    "getent hosts 1981.localhost.mene.ro"\
    "getent hosts 1982.localhost.mene.ro"\
    "getent hosts 1983.localhost.mene.ro"\
    "getent hosts 1984.localhost.mene.ro"\
    "getent hosts 1985.localhost.mene.ro"\
    "getent hosts 1986.localhost.mene.ro"\
    "getent hosts 1987.localhost.mene.ro"\
    "getent hosts 1988.localhost.mene.ro"\
    "getent hosts 1989.localhost.mene.ro"\
    "getent hosts 1990.localhost.mene.ro"\
    "getent hosts 1991.localhost.mene.ro"\
    "getent hosts 1992.localhost.mene.ro"\
    "getent hosts 1993.localhost.mene.ro"\
    "getent hosts 1994.localhost.mene.ro"\
    "getent hosts 1995.localhost.mene.ro"\
    "getent hosts 1996.localhost.mene.ro"\
    "getent hosts 1997.localhost.mene.ro"\
    "getent hosts 1998.localhost.mene.ro"\
    "getent hosts 1999.localhost.mene.ro"\
    "getent hosts 2000.localhost.mene.ro"\
    "getent hosts 2001.localhost.mene.ro"\
    "getent hosts 2002.localhost.mene.ro"\
    "getent hosts 2003.localhost.mene.ro"\
    "getent hosts 2004.localhost.mene.ro"\
    "getent hosts 2005.localhost.mene.ro"\
    ;

printf "\nall done.\n";
