#!/bin/bash

TEXT_RESET=$(tput sgr0);
TEXT_COLOR_RED=$(tput setaf 1);
TEXT_COLOR_BLUE=$(tput setaf 4);
TEXT_TYPE_BOLD=$(tput bold);

TEXT_ERROR=$TEXT_COLOR_RED$TEXT_TYPE_BOLD;
TEXT_INFO=$TEXT_COLOR_BLUE$TEXT_TYPE_BOLD;
